no configuration file is a fatal error so exit with 1 in init scripts

diff --git a/src/services/cache_service/arc-cache-service.in b/src/services/cache_service/arc-cache-service.in
--- a/src/services/cache_service/arc-cache-service.in
+++ b/src/services/cache_service/arc-cache-service.in
@@ -173,8 +173,8 @@ prepare() {
     fi
 
     if [ ! -r "$ARC_CONFIG" ]; then
-	log_warning_msg "ARC configuration not found (usually /etc/arc.conf)"
-	exit 0
+	log_failure_msg "ARC configuration not found (usually /etc/arc.conf)"
+	exit 1
     fi
 
     # Creating configuration file of arched
diff --git a/src/services/gridftpd/gridftpd.init.in b/src/services/gridftpd/gridftpd.init.in
--- a/src/services/gridftpd/gridftpd.init.in
+++ b/src/services/gridftpd/gridftpd.init.in
@@ -152,8 +152,8 @@ if [ "x$ARC_CONFIG" = "x" ]; then
 fi
 
 if [ ! -r "$ARC_CONFIG" ]; then
-    log_warning_msg "ARC configuration not found (usually /etc/arc.conf)"
-    exit 0
+    log_failure_msg "ARC configuration not found (usually /etc/arc.conf)"
+    exit 1
 fi
 
 CMD="$CMD -c '$ARC_CONFIG'"
diff --git a/src/services/ldap-infosys/grid-infosys.in b/src/services/ldap-infosys/grid-infosys.in
--- a/src/services/ldap-infosys/grid-infosys.in
+++ b/src/services/ldap-infosys/grid-infosys.in
@@ -171,9 +171,9 @@ if [ ! -r "$ARC_CONFIG" ]; then
 	echo "Fallback /etc/nordugrid.conf was found, trying to use that one"
 	ARC_CONFIG="/etc/nordugrid.conf"
     else
-	log_warning_msg "arc.conf was not found. If this file is in a non-standard place,"
-	log_warning_msg "  it can be set with the ARC_CONFIG environment variable"
-	exit 0
+	log_failure_msg "arc.conf was not found. If this file is in a non-standard place,"
+	log_failure_msg "  it can be set with the ARC_CONFIG environment variable"
+	exit 1
     fi
 fi
 
