use common config parse in datadelivery service init scripts

diff --git a/src/services/data-staging/arc-datadelivery-service-start.in b/src/services/data-staging/arc-datadelivery-service-start.in
--- a/src/services/data-staging/arc-datadelivery-service-start.in
+++ b/src/services/data-staging/arc-datadelivery-service-start.in
@@ -55,42 +55,14 @@ if [ ! -d "$ARC_LOCATION" ]; then
 fi
 export ARC_LOCATION
 
-# Needed to get pid file
-readconfigvar() {
-    fname=$1
-    if [ ! -r "$fname" ]; then
-        return
+readorigconfigvar() {
+    value=`$ARC_LOCATION/@pkglibexecsubdir@/arcconfig-parser --config "$1" -b "$2" -o "$3" 2>/dev/null`
+    if [ "$?" = '0' ] ; then
+        echo "$value"
+        exit 0
+    else
+        exit 1
     fi
-    bname="[$2]"
-    vname=$3
-    value=
-    cat "$fname" | grep -e '^\[' -e "^${vname}[[:space:]]*=" | {
-        while true; do
-            read line
-            if [ ! $? = 0 ] ; then
-                return
-            fi
-            if [ "$line" = "$bname" ] ; then
-                while true ; do
-                    read line
-                    if [ ! $? = 0 ] ; then
-                        return
-                    fi
-                    lstart=`echo "$line" | head -c 1`
-                    if [ "$lstart" = '[' ] ; then
-                        return
-                    fi
-                    vlname=`echo "$line" | sed 's/=.*//;t;s/.*//'`
-                    vlname=`eval "echo $vlname"`
-                    if [ "$vlname" = "$vname" ] ; then
-                        val=`echo "$line" | sed 's/[^=]*=//'`
-                        eval "echo $val"
-                        return
-                    fi
-                done
-            fi
-        done
-    }
 }
 
 # ARC_CONFIG
@@ -102,21 +74,20 @@ if [ "x$ARC_CONFIG" = "x" ]; then
     fi
 fi
 
-PID_FILE=`readconfigvar "$ARC_CONFIG" common pidfile`
-
-if [ `id -u` = 0 ] ; then
-    if [ "x$PID_FILE" = "x" ]; then
-        PID_FILE=/var/run/arc/datadelivery-service.pid
-    fi
-else
-    if [ "x$PID_FILE" = "x" ]; then
-        PID_FILE=$HOME/datadelivery-service.pid
-    fi
+PID_FILE=`readorigconfigvar "$ARC_CONFIG" datadelivery-service pidfile`
+if [ "x$PID_FILE" = "x" ]; then
+    # Missing default value for pidfile means no service block is present
+    log_failure_msg "ARC configuration is missing [datadelivery-service] block"
+    exit 1
 fi
 
-LOG_FILE=`readconfigvar "$ARC_CONFIG" common logfile`
+LOG_FILE=`readorigconfigvar "$ARC_CONFIG" datadelivery-service logfile`
 if [ "x$LOG_FILE" = "x" ]; then
-    LOG_FILE=/var/log/arc/datadelivery-service.log
+    log_failure_msg "Log file could not be found in [datadelivery-service] block"
+    exit 1
+fi
+if [ ! -d `dirname "$LOGFILE"` ]; then
+    mkdir -p `dirname "$LOGFILE"`
 fi
 
 prepare() {
@@ -131,17 +102,10 @@ prepare() {
         echo "ARC configuration not found (usually /etc/arc.conf)"
         exit 1
     fi
-    
-    # check that at least service is defined
-    grep -e '^\[datadelivery-service\]' $ARC_CONFIG 1>/dev/null 2>&1
-    if [ $? -ne 0 ] ; then
-        echo "Data delivery service not defined in configuration"
-        exit 1
-    fi
-    
+
     # check that if service is insecure no allowed_dns are defined
-    SECURE=`readconfigvar "$ARC_CONFIG" common secure`
-    ALLOWEDDN=`readconfigvar "$ARC_CONFIG" datadelivery-service allowed_dn`
+    SECURE=`readorigconfigvar "$ARC_CONFIG" datadelivery-service secure`
+    ALLOWEDDN=`readorigconfigvar "$ARC_CONFIG" datadelivery-service allowed_dn`
     if [ "$SECURE" = "no" ]; then
         if [ "x$ALLOWEDDN" != "x" ]; then
             echo "allowed_dn cannot be used with secure=no"
