Do not call exit code handling if sacct failed.

diff --git a/src/services/a-rex/lrms/slurm/scan-SLURM-job.in b/src/services/a-rex/lrms/slurm/scan-SLURM-job.in
--- a/src/services/a-rex/lrms/slurm/scan-SLURM-job.in
+++ b/src/services/a-rex/lrms/slurm/scan-SLURM-job.in
@@ -139,7 +139,7 @@ fi
 
 # Get JobStates from SLURM
 jobstate_squeue=$(echo "${lidblocks[@]}" | xargs -n 1 $squeue -a -h -o "%i:%T" -t all -j )\
-    || { echo "squeue failed" 1>&2; exit 1; }
+    || { echo "[$(date  +%Y-%m-%d\ %T)] squeue failed" 1>&2; exit 1; }
 
 for record in $jobstate_squeue; do
     localid=$(echo "$record"|cut -d: -f1)
@@ -286,10 +286,12 @@ function handle_diag_file {
     job_read_diag
 
     handle_diag_tries=3
-    ## This while loop is an attempt to reduce the cases where the job info is not successfully fetched from slurm due to slurm connection/timeout issues
+    ## This while loop is an attempt to reduce the cases where the job info
+    ## is not successfully fetched from slurm due to slurm connection/timeout issues
     while [ "$handle_diag_tries" -gt 0 ] ; do
 	    if [ "$use_sacct" ]; then 
-            jobinfostring=$("$sacct" -j $localid.batch -o NCPUS,NNODES,CPUTimeRAW,Start,End,UserCPU,SystemCPU,ExitCode,State -P | tail -n 1)
+		jobinfostring=$("$sacct" -j $localid.batch -o NCPUS,NNODES,CPUTimeRAW,Start,End,UserCPU,SystemCPU,ExitCode,State -P | tail -n 1) \
+		    || { echo "\"[$(date  +%Y-%m-%d\ %T)]\" sacct failed - could not fetch jobinfostring" 1>&2; jobinfo_failed=1;}
 	    
 	        cpus=$(echo "$jobinfostring" | awk -F'|' '{print $1}')
 
@@ -297,13 +299,14 @@ function handle_diag_file {
 
 	        endtime=$(echo "$jobinfostring"|awk -F'|' '{print $5}'| sed 's,\([0-9]\+/[0-9]\+\)-\([0-9:]\+\),\1 \2,g' | sed 's/T/ /g')
 
-            # UserCPU,SystemCPU format is [dd-]hh:mm:ss[.uuu]
-            usercputime=$(echo "$jobinfostring" | awk -F'|' '{print $6}')
-            kernelcputime=$(echo "$jobinfostring" | awk -F'|' '{print $7}')
-            [ -z "$usercputime" ] && usercputime="00:00:00"
-            [ -z "$kernelcputime" ] && kernelcputime="00:00:00"
+		# UserCPU,SystemCPU format is [dd-]hh:mm:ss[.uuu]
+		usercputime=$(echo "$jobinfostring" | awk -F'|' '{print $6}')
+		kernelcputime=$(echo "$jobinfostring" | awk -F'|' '{print $7}')
+		[ -z "$usercputime" ] && usercputime="00:00:00"
+		[ -z "$kernelcputime" ] && kernelcputime="00:00:00"
 	    else
-	        jobinfostring=$("$scontrol" -o show job $localid)
+	        jobinfostring=$("$scontrol" -o show job $localid) \
+		    || { echo "\"[$(date  +%Y-%m-%d\ %T)]\" scontrol failed - could not fetch jobinfostring" 1>&2; jobinfo_failed=1;}
 
 	        #Slurm can report StartTime and EndTime in at least these two formats:
 	        #2010-02-15T15:30:29
@@ -321,16 +324,16 @@ function handle_diag_file {
 	    ## The latter is handled already in handle_diag_file function
 	    ## If (not empty cpus variable, and cpus variable is a number) or cpus variable is NCPUS then we are done, so break out of the retry loop  
 	    if ( [   -n "$cpus" ]  &&  [ "$cpus" -eq "$cpus" ]  2>/dev/null ) ||   [ z"$cpus" = "zNCPUS" ] ; then break ; fi
-	    sleep 3
+	    sleep 1
 	    handle_diag_tries=$(( $handle_diag_tries - 1 ))
 	    if [ "$handle_diag_tries" -lt 3 ] ; then
-	        now=$(date +"%Y-%m-%d -%H:%M:%S")
-	        echo "scan-SLURM-job: \"$now\" - handle_diag_tries: \"$handle_diag_tries\" for job \"$localid\" - got cpu value \"$cpus\"\n" 1>&2
+	        echo "scan-SLURM-job: \"[$(date  +%Y-%m-%d\ %T)]\" handle_diag_tries: \"$handle_diag_tries\" for job \"$localid\" - got cpu value \"$cpus\"" 1>&2
+		echo "scan-SLURM-job: \"[$(date  +%Y-%m-%d\ %T)]\" jobinfo_failed var is: \"$jobinfo_failed\" " 1>&2
 	    fi
     done
 
     # if "sacct -j $localid.batch" return string "NCPUS|NNodes..." only, the job has no batch stage, it was killed before start on WN
-    if [ ! z"$cpus" = "zNCPUS" ] ; then
+    if [ ! z"$cpus" = "zNCPUS" ] && [ -z jobinfo_failed ]; then
         date_to_utc_seconds "$starttime"
         starttime_seconds="$return_date_seconds"
         seconds_to_mds_date "$return_date_seconds"
@@ -424,39 +427,44 @@ for localid in ${localids[@]}; do
 
  	    ;;
   	PENDING|RUNNING|SUSPENDE|COMPLETING)
-  	#Job is running, nothing to do.
-        run=$(($run + 1))
+  	    #Job is running, nothing to do.
+            run=$(($run + 1))
   	    ;;
 	CANCELLED)
-        failed=$(($failed + 1))
+            failed=$(($failed + 1))
 	    handle_commentfile $localid
 	    kicklist=(${kicklist[@]} $localid)
 	    handle_diag_file "$localid" "${basenames[$localid]}.diag"
-	    handle_exitcode_cancelled $localid "-1" "Job was cancelled"
+	    echo "[$(date  +%Y-%m-%d\ %T)] \"$localid\" CANCELLED, but jobinfo_failed - not setting exit code, will try again in next scan" 1>&2
+	    [ -z "$jobinfo_failed" ] && handle_exitcode_cancelled $localid "-1" "Job was cancelled" || { echo "[$(date  +%Y-%m-%d\ %T)] jobinfo_failed - not setting exit code" 1>&2; }
 	    ;;
 	COMPLETED)
-        done=$(($done + 1))
-        handle_commentfile $localid
-        handle_diag_file "$localid" "${basenames[$localid]}.diag"
-	    handle_exitcode $localid "0" ""
+            done=$(($done + 1))
+            handle_commentfile $localid
+            handle_diag_file "$localid" "${basenames[$localid]}.diag"
+	    echo "[$(date  +%Y-%m-%d\ %T)] \"$localid\" COMPLETED, but jobinfo_failed - not setting exit code, will try again in next scan" 1>&2
+	    [ -z "$jobinfo_failed" ] && handle_exitcode $localid "0" "" || { echo "[$(date  +%Y-%m-%d\ %T)] jobinfo_failed - not setting exit code" 1>&2; }
 	    ;;
 	FAILED)
 	    failed=$(($failed + 1))
 	    handle_commentfile $localid
 	    handle_diag_file "$localid" "${basenames[$localid]}.diag"
-	    handle_exitcode $localid "-1" "Job failed"
+	    echo "[$(date  +%Y-%m-%d\ %T)] \"$localid\" FAILED, but jobinfo_failed - not setting exit code, will try again in next scan" 1>&2
+	    [ -z "$jobinfo_failed" ] && handle_exitcode $localid "-1" "Job failed" || { echo "[$(date  +%Y-%m-%d\ %T)] jobinfo_failed - not setting exit code" 1>&2; }
 	    ;;
 	TIMEOUT)
 	    failed=$(($failed + 1))
 	    handle_commentfile $localid
 	    handle_diag_file "$localid" "${basenames[$localid]}.diag"
-	    handle_exitcode $localid "-1" "Job timeout"
+	    echo "[$(date  +%Y-%m-%d\ %T)] \"$localid\" TIMEOUT, but jobinfo_failed - not setting exit code, will try again in next scan" 1>&2
+	    [ -z "$jobinfo_failed" ] && handle_exitcode $localid "-1" "Job timeout" || { echo "[$(date  +%Y-%m-%d\ %T)] jobinfo_failed - not setting exit code" 1>&2; }
 	    ;;
 	NODE_FAIL)
 	    failed=$(($failed + 1))
 	    handle_commentfile $localid
 	    handle_diag_file "$localid" "${basenames[$localid]}.diag"
-	    handle_exitcode_cancelled $localid "-1" "Node fail"
+	    echo "[$(date  +%Y-%m-%d\ %T)] \"$localid\" NODE_FAIL, but jobinfo_failed - not setting exit code, will try again in next scan" 1>&2
+	    [ -z "$jobinfo_failed" ] && handle_exitcode_cancelled $localid "-1" "Node fail" || { echo "[$(date  +%Y-%m-%d\ %T)] jobinfo_failed - not setting exit code" 1>&2; }
 	    ;;
     esac
 done
