Added a check for a valid jobid in the slurm backend (BUG: 3403)

diff --git a/src/services/a-rex/lrms/slurm/submit-SLURM-job.in b/src/services/a-rex/lrms/slurm/submit-SLURM-job.in
--- a/src/services/a-rex/lrms/slurm/submit-SLURM-job.in
+++ b/src/services/a-rex/lrms/slurm/submit-SLURM-job.in
@@ -421,12 +421,10 @@ if [ $SLURM_RESULT -eq '0' ] ; then
    # SLURM 1.x and 2.2.x outputs the jobid into STDERR and STDOUT respectively. Concat them,
    # and let sed sort it out. From the exit code we know that the job was submitted, so this
    # is safe. Ulf Tigerstedt <tigerste@csc.fi> 1.5.2011 
+   # This is unfortunately not safe. Cray's SLURM sbatch returns 0, when it fails to submit a job. <soettrup@nbi.dk> 22.1.2015
+
    job_id=`cat $LRMS_JOB_OUT $LRMS_JOB_ERR |sed -e 's/^\(sbatch: \)\{0,1\}Submitted batch job \([0-9]*\)$/\2/'`
-   if [ "${job_id}" = "" ] ; then
-      echo "job *NOT* submitted successfully!" 1>&2
-      echo "failed getting the slurm jobid for the job!" 1>&2
-      echo "Submission: Local submission client behaved unexpectedly.">>"$failures_file"
-   else
+   if expr match "${job_id}" '[0-9][0-9]*' >/dev/null; then
       echo "joboption_jobid=$job_id" >> $arg_file
       echo "job submitted successfully!" 1>&2
       echo "local job id: $job_id" 1>&2
@@ -435,6 +433,11 @@ if [ $SLURM_RESULT -eq '0' ] ; then
       echo "----- exiting submit_slurm_job -----" 1>&2
       echo "" 1>&2
       exit 0
+   else
+      echo "job *NOT* submitted successfully!" 1>&2
+      echo "failed getting the slurm jobid for the job!" 1>&2
+      echo "Instead got: ${job_id}" 1>&2
+      echo "Submission: Local submission client behaved unexpectedly.">>"$failures_file"
    fi
 else
   echo "job *NOT* submitted successfully!" 1>&2
