Remove extra '>'. Fix for bug #3029

diff --git a/src/services/a-rex/lrms/pbs/submit-pbs-job.in b/src/services/a-rex/lrms/pbs/submit-pbs-job.in
--- a/src/services/a-rex/lrms/pbs/submit-pbs-job.in
+++ b/src/services/a-rex/lrms/pbs/submit-pbs-job.in
@@ -167,7 +167,7 @@ if [ ! -z $joboption_exclusive && $joboption_exclusive = 'yes' ] ; then
      memreq="${tempmem}"
    fi
   else
-    echo "WARNING: Could not set memory limit to simulate exclusice execution." > 1>&2
+    echo "WARNING: Could not set memory limit to simulate exclusice execution." 1>&2
   fi 
 fi
 
