common submit for all shell-backends
(cherry picked from commit a57eb88e77079982101f3007e751a00edf9439f1)

diff --git a/src/services/a-rex/lrms/submit_common.sh.in b/src/services/a-rex/lrms/submit_common.sh.in
--- a/src/services/a-rex/lrms/submit_common.sh.in
+++ b/src/services/a-rex/lrms/submit_common.sh.in
@@ -36,6 +36,23 @@ common_init () {
     init_lrms_env
 }
 
+# defines failures_file
+define_failures_file () {
+    failures_file="$joboption_controldir/job.$joboption_gridid.failed"
+}
+
+
+# checks any scratch is defined (shared or local)
+check_any_scratch () {
+    if [ -z "${RUNTIME_NODE_SEES_FRONTEND}" ] ; then
+        if [ -z "${RUNTIME_LOCAL_SCRATCH_DIR}" ] ; then
+            echo "Need to know at which directory to run job: RUNTIME_LOCAL_SCRATCH_DIR must be set if RUNTIME_NODE_SEES_FRONTEND is empty" 1>&2
+            echo "Submission: Configuration error.">>"$failures_file"
+            exit 1
+        fi
+    fi
+}
+
 #
 # Sets a default memory limit for jobs that don't have one
 #
