new RunTimeEnvironemnt handling approach for next major release

diff --git a/src/services/a-rex/lrms/submit_common.sh.in b/src/services/a-rex/lrms/submit_common.sh.in
--- a/src/services/a-rex/lrms/submit_common.sh.in
+++ b/src/services/a-rex/lrms/submit_common.sh.in
@@ -187,53 +187,6 @@ set_count () {
 }
 
 ##############################################################
-# Zero stage of runtime environments
-##############################################################
-# should we write failures to job.111.failed like the old pbs?
-
-RTE_stage0 () {
-   joboption_num=0
-   eval "var_is_set=\${joboption_runtime_$joboption_num+yes}"
-   while [ ! -z "${var_is_set}" ] ; do
-      eval "var_value=\${joboption_runtime_$joboption_num}"
-      if [ -r "$RUNTIME_CONFIG_DIR/${var_value}" ] ; then
-         arg_num=1
-         args_value="0 "
-         eval "arg_is_set=\${joboption_runtime_${joboption_num}_${arg_num}+yes}"
-         while [ ! -z "${arg_is_set}" ] ; do
-            eval "arg_value=\${joboption_runtime_${joboption_num}_${arg_num}}"
-            # Use -- to avoid echo eating arguments it understands
-            arg_value=`echo -- "$arg_value" |cut -f2- -d' '| sed 's/\\\\/\\\\\\\\/g' | sed 's/"/\\\"/g'`
-            args_value="$args_value \"${arg_value}\""
-            arg_num=$(( $arg_num + 1 ))
-            eval "arg_is_set=\${joboption_runtime_${joboption_num}_${arg_num}+yes}"
-         done
-         #eval ". \"$RUNTIME_CONFIG_DIR/${var_value}\" $args_value" 1>&2
-         cmdl="$RUNTIME_CONFIG_DIR/${var_value}"
-         sourcewithargs $cmdl $args_value 1>&2
-	 if [ $? -ne '0' ] ; then
-            echo "ERROR: runtime script ${var_value} failed" 1>&2
-            exit 1
-         fi
-      else
-         echo "Warning: runtime script ${var_value} is missing" 1>&2
-         #should we exit here?
-      fi
-      joboption_num=$(( $joboption_num + 1 ))
-      eval "var_is_set=\${joboption_runtime_$joboption_num+yes}"
-   done
-
-  # joboption_count might have been changed by an RTE. Save it for accounting purposes.
-  if [ -n "$joboption_count" ]; then
-    diagfile="${joboption_controldir}/job.${joboption_gridid}.diag"
-    echo "Processors=$joboption_count" >> "$diagfile"
-    if [ -n "$joboption_numnodes" ]; then
-      echo "Nodecount=$joboption_numnodes" >> "$diagfile"
-    fi
-  fi
-}
-
-##############################################################
 # create temp job script
 ##############################################################
 
@@ -303,54 +256,132 @@ sourcewithargs_jobscript () {
 }
 
 ##############################################################
-#  Runtime configuration
+#  RunTimeEnvironemt Functions
 ##############################################################
-RTE_stage1 () {
-   echo "# Running runtime scripts" >> $LRMS_JOB_SCRIPT
-   
-   echo "export RUNTIME_CONFIG_DIR=\${RUNTIME_CONFIG_DIR:-$RUNTIME_CONFIG_DIR}" >> $LRMS_JOB_SCRIPT
-   i=0
-   eval "var_is_set=\${joboption_runtime_$i+yes}"
-   echo "runtimeenvironments=" >> $LRMS_JOB_SCRIPT
-   while [ ! -z "${var_is_set}" ] ; do
-      if [ "$i" = '0' ] ; then
-         echo "if [ ! -z \"\$RUNTIME_CONFIG_DIR\" ] ; then" >> $LRMS_JOB_SCRIPT
-      fi
-      eval "var_value=\"\${joboption_runtime_$i}\""
-      echo "  if [ -r \"\${RUNTIME_CONFIG_DIR}/${var_value}\" ] ; then" >> $LRMS_JOB_SCRIPT
-      echo "    runtimeenvironments=\"\${runtimeenvironments}${var_value};\"" >> $LRMS_JOB_SCRIPT
-      arg_num=1
-      args_value="1 "
-      eval "arg_is_set=\${joboption_runtime_${i}_${arg_num}+yes}"
-      while [ ! -z "${arg_is_set}" ] ; do
-         eval "arg_value=\${joboption_runtime_${i}_${arg_num}}"
-         # Use -- to avoid echo eating arguments it understands
-         arg_value=`printf "%s" "$arg_value" | sed 's/"/\\\\\\\"/g'`
-         args_value="$args_value \"${arg_value}\""
-         arg_num=$(( $arg_num + 1 ))
-         eval "arg_is_set=\${joboption_runtime_${i}_${arg_num}+yes}"
-      done
-      #echo "    . \${RUNTIME_CONFIG_DIR}/${var_value} $args_value " >> $LRMS_JOB_SCRIPT
-      echo "    cmdl=\${RUNTIME_CONFIG_DIR}/${var_value} " >> $LRMS_JOB_SCRIPT
-      printf "    sourcewithargs \$cmdl $args_value \n" >> $LRMS_JOB_SCRIPT
-
-      echo "    if [ \$? -ne '0' ] ; then " >> $LRMS_JOB_SCRIPT
-      echo "      echo \"Runtime ${var_value} script failed \" 1>&2 " >> $LRMS_JOB_SCRIPT
-      echo "      echo \"Runtime ${var_value} script failed \" 1>\"\$RUNTIME_JOB_DIAG\" " >> $LRMS_JOB_SCRIPT
-      echo "      exit 1" >> $LRMS_JOB_SCRIPT
-      echo "    fi " >> $LRMS_JOB_SCRIPT
-      echo "  fi" >> $LRMS_JOB_SCRIPT
-      i=$(( $i + 1 ))
-      eval "var_is_set=\${joboption_runtime_$i+yes}"
-   done
-
-   if [ ! "$i" = '0' ] ; then
-     echo "fi" >> $LRMS_JOB_SCRIPT
-   fi
-
-   echo "" >> $LRMS_JOB_SCRIPT
+RTE_path_set () {
+    # search for RTE file (defined in 'rte_name' variable in user-defined and system locations and set 'rte_path' variable
+    rte_path="${RUNTIME_CONFIG_DIR}/${rte_name}"
+    if [ ! -f "$rte_path" ]; then
+        rte_path="${pkgdatadir}/rte/${rte_name}"
+        if [ ! -f "$rte_path" ]; then
+            echo "ERROR: Requested RunTimeEnvironment ${rte_name} is missing in the both user-defined and system locations." 1>&2
+            exit 1
+        fi 
+    fi
 }
 
+RTE_add_optional_args () {
+    # for RTE defined by 'rte_idx' adds optional arguments to 'args_value' if any
+    arg_idx=1
+    eval "is_arg=\${joboption_runtime_${rte_idx}_${arg_idx}+yes}"
+    while [ -n "${is_arg}" ] ; do
+        eval "arg_value=\${joboption_runtime_${rte_idx}_${arg_idx}}"
+        # Use -- to avoid echo eating arguments it understands
+        arg_value=$( printf "%s" "$arg_value" | sed 's/"/\\\\\\\"/g' )
+        args_value="$args_value \"${arg_value}\""
+        arg_idx=$(( arg_idx + 1 ))
+        eval "is_arg=\${joboption_runtime_${rte_idx}_${arg_idx}+yes}"
+    done
+    unset arg_idx arg_value is_arg 
+}
+
+RTE_to_jobscript () {
+    rte_idx=0
+    eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+    while [ -n "${is_rte}" ] ; do
+        eval "rte_name=\"\${joboption_runtime_${rte_idx}}\""
+        # define rte_path
+        RTE_path_set
+        # add RTE script content as a function into the job script
+        echo "# RunTimeEnvironment function for ${rte_name}:" >> $LRMS_JOB_SCRIPT
+        echo "RTE_function_${rte_idx} () {" >> $LRMS_JOB_SCRIPT
+        cat "${rte_path}" >> $LRMS_JOB_SCRIPT
+        echo "}" >> $LRMS_JOB_SCRIPT
+        # next RTE
+        rte_idx=$(( rte_idx + 1 ))
+        eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+    done
+    unset is_rte rte_idx rte_name rte_path
+}
+
+RTE_jobscript_call () {
+    rte_stage=$1
+    if [ "$rte_stage" = '1' ]; then
+        RTE_to_jobscript
+    fi
+    echo "# Running RTE scripts (stage ${rte_stage})" >> $LRMS_JOB_SCRIPT
+    echo "runtimeenvironments=" >> $LRMS_JOB_SCRIPT
+
+    rte_idx=0
+    eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+    while [ -n "${is_rte}" ] ; do
+        # RTE name is for admin-friendly logging only
+        eval "rte_name=\"\${joboption_runtime_${rte_idx}}\""
+        echo "runtimeenvironments=\"\${runtimeenvironments}${rte_name};\"" >> $LRMS_JOB_SCRIPT
+        # compose arguments value for RTE function call
+        args_value="${rte_stage} "
+        RTE_add_optional_args
+        # add function call to job script
+        echo "# Calling ${rte_name} function: " $LRMS_JOB_SCRIPT
+        echo "RTE_function_${rte_idx} ${args_value}" >> $LRMS_JOB_SCRIPT
+        echo "if [ \$? -ne 0 ]; then" >> $LRMS_JOB_SCRIPT
+        echo "    echo \"Runtime ${rte_name} stage ${rte_stage} execution failed.\" 1>&2" >> $LRMS_JOB_SCRIPT
+        echo "    echo \"Runtime ${rte_name} stage ${rte_stage} execution failed.\" 1>\"\${RUNTIME_JOB_DIAG}\"" >> $LRMS_JOB_SCRIPT
+        echo "    exit 1" >> $LRMS_JOB_SCRIPT
+        echo "fi" >> $LRMS_JOB_SCRIPT
+        echo "" >> $LRMS_JOB_SCRIPT
+        rte_idx=$(( rte_idx + 1 ))
+        eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+    done
+    unset rte_idx is_rte rte_name args_value rte_stage
+}
+
+RTE_stage0 () {
+    rte_idx=0
+    eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+    while [ -n "${is_rte}" ] ; do
+        eval "rte_name=\"\${joboption_runtime_${rte_idx}}\""
+    # define rte_path
+    RTE_path_set
+    # define arguments
+    args_value="0 "
+    RTE_add_optional_args
+    # run RTE stage 0
+    # WARNING!!! IN SOME CASES DUE TO DIRECT SOURCING OF RTE SCRIPT WITHOUT ANY SAFETY CHECKS 
+    #            SPECIALLY CRAFTED RTES CAN BROKE CORRECT SUBMISSION (e.g. RTE redefine 'rte_idx' variable)
+    sourcewithargs "$rte_path" $args_value 1>&2
+    rte0_exitcode=$?
+    if [ $rte0_exitcode -ne 0 ] ; then
+            echo "ERROR: Runtime script ${rte_name} stage 0 execution failed with exit code ${rte0_exitcode}" 1>&2
+            exit 1
+    fi
+        rte_idx=$(( rte_idx + 1 ))
+        eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+    done
+
+    # joboption_count might have been changed by an RTE. Save it for accounting purposes.
+    if [ -n "$joboption_count" ]; then
+        diagfile="${joboption_controldir}/job.${joboption_gridid}.diag"
+        echo "Processors=$joboption_count" >> "$diagfile"
+        if [ -n "$joboption_numnodes" ]; then
+            echo "Nodecount=$joboption_numnodes" >> "$diagfile"
+        fi
+    fi
+    unset rte_idx is_rte rte_name rte_path rte0_exitcode
+}
+
+RTE_stage1 () {
+    RTE_jobscript_call 1
+}
+
+RTE_stage2 () {
+    RTE_jobscript_call 2
+}
+
+#TODO: rename to RTE_stage2 in all LRMS backends
+configure_runtime () {
+    RTE_stage2
+}
 
 ##############################################################
 # Add std... to job arguments
@@ -371,41 +402,6 @@ include_std_streams () {
       output_redirect="$output_redirect 2>\$RUNTIME_JOB_STDERR"
     fi
   fi
-}
-
-##############################################################
-# Runtime configuration
-##############################################################
-configure_runtime () {
-  i=0
-  eval "var_is_set=\${joboption_runtime_$i+yes}"
-  while [ ! -z "${var_is_set}" ] ; do
-    if [ "$i" = '0' ] ; then
-      echo "if [ ! -z \"\$RUNTIME_CONFIG_DIR\" ] ; then" >> $LRMS_JOB_SCRIPT
-    fi
-    eval "var_value=\"\${joboption_runtime_$i}\""
-    echo "  if [ -r \"\${RUNTIME_CONFIG_DIR}/${var_value}\" ] ; then" >> $LRMS_JOB_SCRIPT
-    arg_num=1
-    args_value="2 "
-    eval "arg_is_set=\${joboption_runtime_${i}_${arg_num}+yes}"
-    while [ ! -z "${arg_is_set}" ] ; do
-      eval "arg_value=\${joboption_runtime_${i}_${arg_num}}"
-      # Use -- to avoid echo eating arguments it understands
-      arg_value=`printf -- "$arg_value" | sed 's/\\\\/\\\\\\\\/g' | sed 's/"/\\\\\\\"/g'`
-      args_value="$args_value \"${arg_value}\""
-      arg_num=$(( $arg_num + 1 ))
-      eval "arg_is_set=\${joboption_runtime_${i}_${arg_num}+yes}"
-    done
-    echo "    cmdl=\${RUNTIME_CONFIG_DIR}/${var_value}" >> $LRMS_JOB_SCRIPT
-    printf "    sourcewithargs \$cmdl $args_value \n" >> $LRMS_JOB_SCRIPT
-    echo "  fi" >> $LRMS_JOB_SCRIPT
-    i=$(( $i + 1 ))
-    eval "var_is_set=\${joboption_runtime_$i+yes}"
-  done
-  if [ ! "$i" = '0' ] ; then
-    echo "fi" >> $LRMS_JOB_SCRIPT
-  fi
-  echo "" >> $LRMS_JOB_SCRIPT
 }
 
 ##############################################################
