Shell backends fixes to reflect RTE enable/disable with arcctl. Default RTEs feature implementation.
(cherry picked from commit d2188a8884e22197bfdc9c8ffe201c3d20790ba8)

diff --git a/src/services/a-rex/lrms/submit_common.sh.in b/src/services/a-rex/lrms/submit_common.sh.in
--- a/src/services/a-rex/lrms/submit_common.sh.in
+++ b/src/services/a-rex/lrms/submit_common.sh.in
@@ -156,7 +156,7 @@ set_req_mem () {
             echo "         A default memory limit taken from 'defaultmemory' in        " 1>&2
             echo "         arc.conf will apply.                                        " 1>&2
             echo "         Limit is: $CONFIG_defaultmemory mb.                         " 1>&2
-	elif is_number "$CONFIG_nodememory"; then
+        elif is_number "$CONFIG_nodememory"; then
             joboption_memory=$CONFIG_nodememory
 
             echo "         A default memory limit taken from 'nodememory' in arc.conf  " 1>&2
@@ -254,15 +254,34 @@ sourcewithargs_jobscript () {
 ##############################################################
 #  RunTimeEnvironemt Functions
 ##############################################################
+RTE_include_default () {
+    default_rte_dir="${CONFIG_controldir}/rte/default/"
+    if [ -d "$default_rte_dir" ]; then
+        # get default RTEs
+        default_rtes=` find "$default_rte_dir" ! -type d | sed "s#^$default_rte_dir##" `
+        if [ -n "$default_rtes" ]; then
+            # Find last RTE index defined
+            rte_idx=0
+            eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+            while [ -n "${is_rte}" ] ; do
+                rte_idx=$(( rte_idx + 1 ))
+                eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
+            done
+            # Add default RTEs to the list
+            for rte_name in $default_rtes; do
+                eval "joboption_runtime_${rte_idx}=$rte"
+                rte_idx=$(( rte_idx + 1 ))
+            done
+        fi
+    fi
+    unset default_rte_dir default_rtes is_rte rte_idx rte_name
+}
+
 RTE_path_set () {
-    # search for RTE file (defined in 'rte_name' variable in user-defined and system locations and set 'rte_path' variable
-    rte_path="${RUNTIME_CONFIG_DIR}/${rte_name}"
+    rte_path="${CONFIG_controldir}/rte/enabled/${rte_name}"
     if [ ! -f "$rte_path" ]; then
-        rte_path="${pkgdatadir}/rte/${rte_name}"
-        if [ ! -f "$rte_path" ]; then
-            echo "ERROR: Requested RunTimeEnvironment ${rte_name} is missing in the both user-defined and system locations." 1>&2
-            exit 1
-        fi 
+        echo "ERROR: Requested RunTimeEnvironment ${rte_name} is missing or not enabled." 1>&2
+        exit 1
     fi
 }
 
@@ -334,24 +353,25 @@ RTE_jobscript_call () {
 }
 
 RTE_stage0 () {
+    RTE_include_default
     rte_idx=0
     eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
     while [ -n "${is_rte}" ] ; do
         eval "rte_name=\"\${joboption_runtime_${rte_idx}}\""
-    # define rte_path
-    RTE_path_set
-    # define arguments
-    args_value="0 "
-    RTE_add_optional_args
-    # run RTE stage 0
-    # WARNING!!! IN SOME CASES DUE TO DIRECT SOURCING OF RTE SCRIPT WITHOUT ANY SAFETY CHECKS 
-    #            SPECIALLY CRAFTED RTES CAN BROKE CORRECT SUBMISSION (e.g. RTE redefine 'rte_idx' variable)
-    sourcewithargs "$rte_path" $args_value 1>&2
-    rte0_exitcode=$?
-    if [ $rte0_exitcode -ne 0 ] ; then
+        # define rte_path
+        RTE_path_set
+        # define arguments
+        args_value="0 "
+        RTE_add_optional_args
+        # run RTE stage 0
+        # WARNING!!! IN SOME CASES DUE TO DIRECT SOURCING OF RTE SCRIPT WITHOUT ANY SAFETY CHECKS 
+        #            SPECIALLY CRAFTED RTES CAN BROKE CORRECT SUBMISSION (e.g. RTE redefine 'rte_idx' variable)
+        sourcewithargs "$rte_path" $args_value 1>&2
+        rte0_exitcode=$?
+        if [ $rte0_exitcode -ne 0 ] ; then
             echo "ERROR: Runtime script ${rte_name} stage 0 execution failed with exit code ${rte0_exitcode}" 1>&2
             exit 1
-    fi
+        fi
         rte_idx=$(( rte_idx + 1 ))
         eval "is_rte=\${joboption_runtime_${rte_idx}+yes}"
     done
