- RTE glob wildcarding functionality - Intruducing RTE parameters to fine-tune RTE behaviour - Requested rte cat feature - Some minor refactoring
(cherry picked from commit 7408762411bb2295e13c9b05de3890ebbaafb00e)

diff --git a/src/services/a-rex/lrms/submit_common.sh.in b/src/services/a-rex/lrms/submit_common.sh.in
--- a/src/services/a-rex/lrms/submit_common.sh.in
+++ b/src/services/a-rex/lrms/submit_common.sh.in
@@ -1,3 +1,4 @@
+#@IgnoreInspection BashAddShebang
 ######################################################
 #Common functions for submit scripts
 ######################################################
@@ -278,10 +279,17 @@ RTE_include_default () {
 }
 
 RTE_path_set () {
+    rte_params_path="${CONFIG_controldir}/rte/params/${rte_name}"
+    if [ ! -f "$rte_params_path" ]; then
+        rte_params_path=""
+    fi
     rte_path="${CONFIG_controldir}/rte/enabled/${rte_name}"
     if [ ! -f "$rte_path" ]; then
-        echo "ERROR: Requested RunTimeEnvironment ${rte_name} is missing or not enabled." 1>&2
-        exit 1
+        rte_path="${CONFIG_controldir}/rte/default/${rte_name}"
+        if [ ! -f "$rte_path" ]; then
+            echo "ERROR: Requested RunTimeEnvironment ${rte_name} is missing or not enabled." 1>&2
+            exit 1
+        fi
     fi
 }
 
@@ -310,6 +318,7 @@ RTE_to_jobscript () {
         # add RTE script content as a function into the job script
         echo "# RunTimeEnvironment function for ${rte_name}:" >> $LRMS_JOB_SCRIPT
         echo "RTE_function_${rte_idx} () {" >> $LRMS_JOB_SCRIPT
+        [ -n "${rte_params_path}" ] && cat "${rte_params_path}" >> $LRMS_JOB_SCRIPT
         cat "${rte_path}" >> $LRMS_JOB_SCRIPT
         echo "}" >> $LRMS_JOB_SCRIPT
         # next RTE
