Print more user friendly error message in case of the absent executable. Fix for bug 3108

diff --git a/src/services/a-rex/lrms/submit_common.sh.in b/src/services/a-rex/lrms/submit_common.sh.in
--- a/src/services/a-rex/lrms/submit_common.sh.in
+++ b/src/services/a-rex/lrms/submit_common.sh.in
@@ -667,10 +667,22 @@ EOSCR
   #TODO this should probably be done on headnode instead
   echo "echo \"ExecutionUnits=${joboption_count}\" >> \"\$RUNTIME_JOB_DIAG\"" >> $LRMS_JOB_SCRIPT
 
+  # In case the job executable does not exist the error message might be
+  # printed by GNU_TIME, which can be confusing for the user.  
+  # This will print more appropriate error message.
+  echo "executable='$joboption_arg_0'" >> $LRMS_JOB_SCRIPT
+  cat >> $LRMS_JOB_SCRIPT <<'EOSCR'
+# Check if executable exists
+if [ ! -f "$executable" ]; 
+then 
+  echo "\"$executable\" is not a valid path to a file" 1>$RUNTIME_JOB_STDOUT 2>$RUNTIME_JOB_STDERR 1>&2
+  exit 1
+fi
+EOSCR
+
   # In case the job executable is written in a scripting language and the
   # interpreter is not found, the error message printed by GNU_TIME is
   # misleading.  This will print a more appropriate error message.
-  echo "executable='$joboption_arg_0'" >> $LRMS_JOB_SCRIPT
   cat >> $LRMS_JOB_SCRIPT <<'EOSCR'
 # See if executable is a script, and extract the name of the interpreter
 line1=`dd if="$executable" count=1 2>/dev/null | head -n 1`
@@ -680,7 +692,7 @@ if [ "$interpreter" = /usr/bin/env ]; then interpreter=`echo $command | awk '{pr
 # If it's a script and the interpreter is not found ...
 [ "x$interpreter" = x ] || type "$interpreter" > /dev/null 2>&1 || {
 
-  echo "Cannot run $executable: $interpreter: not found" "$output_redirect 1>&2"
+  echo "Cannot run $executable: $interpreter: not found" 1>$RUNTIME_JOB_STDOUT 2>$RUNTIME_JOB_STDERR 1>&2
   exit 1; }
 EOSCR
     # Check that gnu_time works
