Cleanup of common lrms code

diff --git a/src/services/a-rex/lrms/submit_common.sh.in b/src/services/a-rex/lrms/submit_common.sh.in
--- a/src/services/a-rex/lrms/submit_common.sh.in
+++ b/src/services/a-rex/lrms/submit_common.sh.in
@@ -597,10 +597,10 @@ interpreter=`echo $command | awk '{print $1}'`
 if [ "$interpreter" = /usr/bin/env ]; then interpreter=`echo $command | awk '{print $2}'`; fi
 # If it's a script and the interpreter is not found ...
 [ "x$interpreter" = x ] || type "$interpreter" > /dev/null 2>&1 || {
-EOSCR
-  echo '  echo "Cannot run $executable: $interpreter: not found"' "$output_redirect 1>&2" >> $LRMS_JOB_SCRIPT
-  echo '  exit 1; }' >> $LRMS_JOB_SCRIPT
 
+  echo "Cannot run $executable: $interpreter: not found" "$output_redirect 1>&2"
+  exit 1; }
+EOSCR
     # Check that gnu_time works
     cat >> $LRMS_JOB_SCRIPT <<EOSCR
 GNU_TIME='$GNU_TIME'
@@ -608,11 +608,11 @@ if [ ! -z "\$GNU_TIME" ] && ! "\$GNU_TIME" --version >/dev/null 2>&1; then
   echo "WARNING: GNU time not found at: \$GNU_TIME" 2>&1;
   GNU_TIME=
 fi 
+
 if [ -z "\$GNU_TIME" ] ; then
-EOSCR
-  echo "  $joboption_args $input_redirect $output_redirect" >> $LRMS_JOB_SCRIPT
-  echo "else" >> $LRMS_JOB_SCRIPT
-  echo "  \"\$GNU_TIME\" -o \"\$RUNTIME_JOB_DIAG\" -a -f '\
+  $joboption_args $input_redirect $output_redirect
+else
+  \$GNU_TIME -o "\$RUNTIME_JOB_DIAG" -a -f '\
 WallTime=%es\nKernelTime=%Ss\nUserTime=%Us\nCPUUsage=%P\n\
 MaxResidentMemory=%MkB\nAverageResidentMemory=%tkB\n\
 AverageTotalMemory=%KkB\nAverageUnsharedMemory=%DkB\n\
@@ -621,9 +621,12 @@ PageSize=%ZB\nMajorPageFaults=%F\nMinorPageFaults=%R\n\
 Swaps=%W\nForcedSwitches=%c\nWaitSwitches=%w\n\
 Inputs=%I\nOutputs=%O\nSocketReceived=%r\nSocketSent=%s\n\
 Signals=%k\n' \
-$joboption_args $input_redirect $output_redirect" >> $LRMS_JOB_SCRIPT
-  echo "fi" >> $LRMS_JOB_SCRIPT
-  echo "RESULT=\$?" >> $LRMS_JOB_SCRIPT
+$joboption_args $input_redirect $output_redirect
+
+fi
+RESULT=\$?
+
+EOSCR
 }
 
 if [ "submit_common.sh" = `basename $0` ]; then
