Removing all references to NORDUGRID_LOCATION. Fixes for initial arguments passing to grid manager.

diff --git a/src/services/a-rex/lrms/ll/scan-ll-job b/src/services/a-rex/lrms/ll/scan-ll-job
--- a/src/services/a-rex/lrms/ll/scan-ll-job
+++ b/src/services/a-rex/lrms/ll/scan-ll-job
@@ -8,23 +8,23 @@
 control_dir="$1"
 test -d "$control_dir" || exit 1
 
-# Get NORDUGRID_LOCATION
-if test "${NORDUGRID_LOCATION}" = ""
+# Get ARC_LOCATION
+if test "${ARC_LOCATION}" = ""
 then
-  NORDUGRID_LOCATION=/opt/nordugrid
-#  echo "NORDUGRID_LOCATION is not set." 1>&2
+  ARC_LOCATION=/opt/nordugrid
+#  echo "ARC_LOCATION is not set." 1>&2
 #  exit 1
 fi
 
 # Get LoadLeveler environment
-if test -f "${NORDUGRID_LOCATION}/libexec/configure-ll-env.sh"
+if test -f "${ARC_LOCATION}/libexec/configure-ll-env.sh"
 then
   :
 else
-  echo "${NORDUGRID_LOCATION}/libexec/configure-ll-env.sh not found." 1>&2
+  echo "${ARC_LOCATION}/libexec/configure-ll-env.sh not found." 1>&2
   exit 1
 fi
-source ${NORDUGRID_LOCATION}/libexec/configure-ll-env.sh
+source ${ARC_LOCATION}/libexec/configure-ll-env.sh
 
 #for i in "$control_dir"/job.*.local
 find $control_dir -maxdepth 1 -type f -name job\*.local | while read i
@@ -76,17 +76,17 @@ do
     if [ "$exitcode" = "152" -o $exitcode = "24" ] ; then
 	exitcode="24"     
     	echo "$exitcode Job exceeded time limit." > "$donefile"
-        ${NORDUGRID_LOCATION}/libexec/gm-kick "$statusfile"
+        ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
         continue  
     fi
     # job finished and exit code is known
     echo "$exitcode Executable finished with exit code $exitcode" >> "$donefile"               
-    ${NORDUGRID_LOCATION}/libexec/gm-kick "$statusfile"
+    ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
     continue
   fi
   exitcode=-1
   echo "$exitcode Job finished with unknown exit code" >> "$donefile"
-  ${NORDUGRID_LOCATION}/libexec/gm-kick "$statusfile"
+  ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
 done
 
 sleep 60
diff --git a/src/services/a-rex/lrms/ll/submit-ll-job b/src/services/a-rex/lrms/ll/submit-ll-job
--- a/src/services/a-rex/lrms/ll/submit-ll-job
+++ b/src/services/a-rex/lrms/ll/submit-ll-job
@@ -11,20 +11,20 @@ echo "----- starting submit_ll_job -----" 1>&2
 joboption_lrms=LL
 
 
-if [ -z ${NORDUGRID_LOCATION} ] ; then
-    echo "NORDUGRID_LOCATION not set." 1>&2
+if [ -z ${ARC_LOCATION} ] ; then
+    echo "ARC_LOCATION not set." 1>&2
     exit 1
 fi
-if [ ! -f "${NORDUGRID_LOCATION}/libexec/configure-ll-env.sh" ] ; then
-    echo "${NORDUGRID_LOCATION}/libexec/configure-ll-env.sh not found." 1>&2
+if [ ! -f "${ARC_LOCATION}/libexec/configure-ll-env.sh" ] ; then
+    echo "${ARC_LOCATION}/libexec/configure-ll-env.sh not found." 1>&2
     exit 1
 fi
-if [ ! -f "${NORDUGRID_LOCATION}/libexec/submit_common.sh" ] ; then
-    echo "${NORDUGRID_LOCATION}/libexec/submit_common.sh not found." 1>&2
+if [ ! -f "${ARC_LOCATION}/libexec/submit_common.sh" ] ; then
+    echo "${ARC_LOCATION}/libexec/submit_common.sh not found." 1>&2
     exit 1
 fi
-. ${NORDUGRID_LOCATION}/libexec/configure-ll-env.sh
-. ${NORDUGRID_LOCATION}/libexec/submit_common.sh
+. ${ARC_LOCATION}/libexec/configure-ll-env.sh
+. ${ARC_LOCATION}/libexec/submit_common.sh
 
 joboption_localtransfer='no'
 
diff --git a/src/services/a-rex/lrms/lsf/scan-lsf-job b/src/services/a-rex/lrms/lsf/scan-lsf-job
--- a/src/services/a-rex/lrms/lsf/scan-lsf-job
+++ b/src/services/a-rex/lrms/lsf/scan-lsf-job
@@ -9,17 +9,17 @@
 #   LSF_BIN_PATH
 
 # "Checking NORDUGRID... "
-if [ -z ${NORDUGRID_LOCATION} ] ; then
-    echo "NORDUGRID_LOCATION not set." 1>&2
+if [ -z ${ARC_LOCATION} ] ; then
+    echo "ARC_LOCATION not set." 1>&2
     exit 1
 fi
-# "Sourcing ${NORDUGRID_LOCATION} config... " 1>&2
-if [ ! -f "${NORDUGRID_LOCATION}/libexec/configure-lsf-env.sh" ] ; then
-    echo "${NORDUGRID_LOCATION}/libexec/configure-lsf-env.sh not found." 1>&2
+# "Sourcing ${ARC_LOCATION} config... " 1>&2
+if [ ! -f "${ARC_LOCATION}/libexec/configure-lsf-env.sh" ] ; then
+    echo "${ARC_LOCATION}/libexec/configure-lsf-env.sh not found." 1>&2
     exit 1
 fi
 
-source ${NORDUGRID_LOCATION}/libexec/configure-lsf-env.sh
+source ${ARC_LOCATION}/libexec/configure-lsf-env.sh
 umask 022
 
 STAT_USERNAME='stat -c %U'
@@ -146,7 +146,7 @@ for ctr_dir in $control_dir ; do
 	    if [ ! -z "$exitcode" ] ; then
 		# job finished and exit code is known
 		echo "$exitcode Executable finished with exit code $exitcode" > "$donefile"
-		${NORDUGRID_LOCATION}/libexec/gm-kick "$statusfile"
+		${ARC_LOCATION}/libexec/gm-kick "$statusfile"
 		continue
 	    fi
 	fi
@@ -163,7 +163,7 @@ for ctr_dir in $control_dir ; do
 	if [ "$counter" -gt 5 ] ; then
 	    rm -f "$countfile"
 	    echo "$exitcode Job was lost with unknown exit code" > "$donefile"
-	    ${NORDUGRID_LOCATION}/libexec/gm-kick "$statusfile"
+	    ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
 	else
 	    echo "$counter" > "$countfile"
 	fi
diff --git a/src/services/a-rex/lrms/lsf/submit-lsf-job b/src/services/a-rex/lrms/lsf/submit-lsf-job
--- a/src/services/a-rex/lrms/lsf/submit-lsf-job
+++ b/src/services/a-rex/lrms/lsf/submit-lsf-job
@@ -30,17 +30,17 @@ fi
 # Set LSF specific environment. # relies on $joboption_queue #
 ##############################################################
 
-if [ -z ${NORDUGRID_LOCATION} ] ; then
-    echo "NORDUGRID_LOCATION not set." 1>&2
+if [ -z ${ARC_LOCATION} ] ; then
+    echo "ARC_LOCATION not set." 1>&2
     exit 1
 fi
 
-if [ ! -f "${NORDUGRID_LOCATION}/libexec/configure-lsf-env.sh" ] ; then
-    echo "${NORDUGRID_LOCATION}/libexec/configure-lsf-env.sh not found." 1>&2
+if [ ! -f "${ARC_LOCATION}/libexec/configure-lsf-env.sh" ] ; then
+    echo "${ARC_LOCATION}/libexec/configure-lsf-env.sh not found." 1>&2
     exit 1
 fi
 
-source ${NORDUGRID_LOCATION}/libexec/configure-lsf-env.sh
+source ${ARC_LOCATION}/libexec/configure-lsf-env.sh
 
 
 # configuration options
@@ -59,7 +59,7 @@ RUNTIME_FRONTEND_SEES_NODE=${RUNTIME_FRONTEND_SEES_NODE:-}
 # enforce this 
 RUNTIME_FRONTEND_SEES_NODE='yes'
 RUNTIME_NODE_SEES_FRONTEND='yes'
-RUNTIME_NORDUGRID_LOCATION="$NORDUGRID_LOCATION"
+RUNTIME_ARC_LOCATION="$ARC_LOCATION"
 RUNTIME_GLOBUS_LOCATION="$GLOBUS_LOCATION"
 
 
@@ -417,11 +417,11 @@ echo "" >> $LRMS_JOB_SCRIPT
 ####################################################
 
 if [ "$joboption_localtransfer" = 'yes' ] ; then
-echo "NORDUGRID_LOCATION=\${NORDUGRID_LOCATION:-$RUNTIME_NORDUGRID_LOCATION}" >> $LRMS_JOB_SCRIPT
+echo "ARC_LOCATION=\${ARC_LOCATION:-$RUNTIME_ARC_LOCATION}" >> $LRMS_JOB_SCRIPT
 echo "GLOBUS_LOCATION=\${GLOBUS_LOCATION:-$RUNTIME_GLOBUS_LOCATION}" >> $LRMS_JOB_SCRIPT
 cat >> $LRMS_JOB_SCRIPT <<'EOSCR'
-if [ -z "$NORDUGRID_LOCATION" ] ; then
-  echo 'Variable NORDUGRID_LOCATION is not set' 1>&2
+if [ -z "$ARC_LOCATION" ] ; then
+  echo 'Variable ARC_LOCATION is not set' 1>&2
   exit 1
 fi
 if [ -z "$GLOBUS_LOCATION" ] ; then
@@ -429,14 +429,14 @@ if [ -z "$GLOBUS_LOCATION" ] ; then
   exit 1
 fi
 export GLOBUS_LOCATION
-export NORDUGRID_LOCATION
+export ARC_LOCATION
 export LD_LIBRARY_PATH="$GLOBUS_LOCATION/lib:$LD_LIBRARY_PATH"
 export SASL_PATH="$GLOBUS_LOCATION/lib/sasl"
 export X509_USER_KEY="${RUNTIME_CONTROL_DIR}/job.local.proxy"
 export X509_USER_CERT="${RUNTIME_CONTROL_DIR}/job.local.proxy"
 export X509_USER_PROXY="${RUNTIME_CONTROL_DIR}/job.local.proxy"
 unset X509_RUN_AS_SERVER
-$NORDUGRID_LOCATION/libexec/downloader -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
+$ARC_LOCATION/libexec/downloader -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
 if [ $? -ne '0' ] ; then
   echo 'ERROR: Downloader failed.' 1>&2
   RESULT=1
@@ -541,7 +541,7 @@ echo "fi" >> $LRMS_JOB_SCRIPT
 if [ "$joboption_localtransfer" = 'yes' ] ; then
 cat >> $LRMS_JOB_SCRIPT <<'EOSCR'
 if [ "$RESULT" = '0' ] ; then
-  $NORDUGRID_LOCATION/libexec/uploader -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
+  $ARC_LOCATION/libexec/uploader -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
   if [ $? -ne '0' ] ; then
     echo 'ERROR: Uploader failed.' 1>&2
     if [ "$RESULT" = '0' ] ; then RESULT=1 ; fi
@@ -584,8 +584,8 @@ cd "$joboption_directory"
 #chmod 0755 $LRMS_JOB_SCRIPT
 
 # We make the assumption that $joboption_directory is locally available according to the requirements of any arc installation
-echo "copying  ${NORDUGRID_LOCATION}/libexec/change-lsf-mode.sh to ${joboption_directory}/change-lsf-mode.sh"  1>&2
-cp -pR $NORDUGRID_LOCATION/libexec/change-lsf-mode.sh $joboption_directory/change-lsf-mode.sh
+echo "copying  ${ARC_LOCATION}/libexec/change-lsf-mode.sh to ${joboption_directory}/change-lsf-mode.sh"  1>&2
+cp -pR $ARC_LOCATION/libexec/change-lsf-mode.sh $joboption_directory/change-lsf-mode.sh
 
 echo "----------------- BEGIN job script -----" 1>&2
 cat $LRMS_JOB_SCRIPT 1>&2
