move non-executable scripts to pkglibdir; updated handling of relative paths

diff --git a/src/services/a-rex/lrms/ll/scan-ll-job.in b/src/services/a-rex/lrms/ll/scan-ll-job.in
--- a/src/services/a-rex/lrms/ll/scan-ll-job.in
+++ b/src/services/a-rex/lrms/ll/scan-ll-job.in
@@ -5,7 +5,10 @@
 #
 
 basedir=`dirname $0`
-basedir=`cd $basedir; pwd`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
+
+pkglibdir="$basedir/@pkglibdir_rel_to_pkglibexecdir@"
+pkglibdir=`cd $pkglibdir > /dev/null && pwd` || exit $?
 
 # Assume that gm-kick is installed in the same directory
 GMKICK=${basedir}/gm-kick
@@ -15,14 +18,14 @@ control_dir="$1"
 test -d "$control_dir" || exit 1
 
 # Get LoadLeveler environment
-if test -f "${basedir}/configure-ll-env.sh"
+if test -f "${pkglibdir}/configure-ll-env.sh"
 then
   :
 else
-  echo "${basedir}/configure-ll-env.sh not found." 1>&2
+  echo "${pkglibdir}/configure-ll-env.sh not found." 1>&2
   exit 1
 fi
-. "${basedir}/configure-ll-env.sh"
+. "${pkglibdir}/configure-ll-env.sh"
 
 #for i in "$control_dir"/job.*.local
 find $control_dir -maxdepth 1 -type f -name job\*.local | while read i
diff --git a/src/services/a-rex/lrms/ll/submit-ll-job.in b/src/services/a-rex/lrms/ll/submit-ll-job.in
--- a/src/services/a-rex/lrms/ll/submit-ll-job.in
+++ b/src/services/a-rex/lrms/ll/submit-ll-job.in
@@ -12,18 +12,21 @@ echo "----- starting submit_ll_job -----" 1>&2
 joboption_lrms=LL
 
 basedir=`dirname $0`
-basedir=`cd $basedir; pwd`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
 
-if [ ! -f "${basedir}/configure-ll-env.sh" ] ; then
-    echo "${basedir}/configure-ll-env.sh not found." 1>&2
+pkglibdir="$basedir/@pkglibdir_rel_to_pkglibexecdir@"
+pkglibdir=`cd $pkglibdir > /dev/null && pwd` || exit $?
+
+if [ ! -f "${pkglibdir}/configure-ll-env.sh" ] ; then
+    echo "${pkglibdir}/configure-ll-env.sh not found." 1>&2
     exit 1
 fi
-if [ ! -f "${basedir}/submit_common.sh" ] ; then
-    echo "${basedir}/submit_common.sh not found." 1>&2
+if [ ! -f "${pkglibdir}/submit_common.sh" ] ; then
+    echo "${pkglibdir}/submit_common.sh not found." 1>&2
     exit 1
 fi
-. ${basedir}/configure-ll-env.sh
-. ${basedir}/submit_common.sh
+. ${pkglibdir}/configure-ll-env.sh
+. ${pkglibdir}/submit_common.sh
 
 joboption_localtransfer='no'
 
diff --git a/src/services/a-rex/lrms/lsf/scan-lsf-job.in b/src/services/a-rex/lrms/lsf/scan-lsf-job.in
--- a/src/services/a-rex/lrms/lsf/scan-lsf-job.in
+++ b/src/services/a-rex/lrms/lsf/scan-lsf-job.in
@@ -9,17 +9,20 @@
 #   LSF_BIN_PATH
 
 basedir=`dirname $0`
-basedir=`cd $basedir; pwd`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
+
+pkglibdir="$basedir/@pkglibdir_rel_to_pkglibexecdir@"
+pkglibdir=`cd $pkglibdir > /dev/null && pwd` || exit $?
 
 # Assume that gm-kick is installed in the same directory
 GMKICK=${basedir}/gm-kick
 
-if [ ! -f "${basedir}/configure-lsf-env.sh" ] ; then
-    echo "${basedir}/configure-lsf-env.sh not found." 1>&2
+if [ ! -f "${pkglibdir}/configure-lsf-env.sh" ] ; then
+    echo "${pkglibdir}/configure-lsf-env.sh not found." 1>&2
     exit 1
 fi
 
-. ${basedir}/configure-lsf-env.sh
+. ${pkglibdir}/configure-lsf-env.sh
 umask 022
 
 STAT_USERNAME='stat -c %U'
diff --git a/src/services/a-rex/lrms/lsf/submit-lsf-job.in b/src/services/a-rex/lrms/lsf/submit-lsf-job.in
--- a/src/services/a-rex/lrms/lsf/submit-lsf-job.in
+++ b/src/services/a-rex/lrms/lsf/submit-lsf-job.in
@@ -10,7 +10,10 @@
 echo "----- starting submit_lsf_job -----" 1>&2
 
 basedir=`dirname $0`
-basedir=`cd $basedir; pwd`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
+
+pkglibdir="$basedir/@pkglibdir_rel_to_pkglibexecdir@"
+pkglibdir=`cd $pkglibdir > /dev/null && pwd` || exit $?
 
 arg_file=$1
 
@@ -32,12 +35,12 @@ fi
 # Set LSF specific environment. # relies on $joboption_queue #
 ##############################################################
 
-if [ ! -f "${basedir}/configure-lsf-env.sh" ] ; then
-    echo "${basedir}/configure-lsf-env.sh not found." 1>&2
+if [ ! -f "${pkglibdir}/configure-lsf-env.sh" ] ; then
+    echo "${pkglibdir}/configure-lsf-env.sh not found." 1>&2
     exit 1
 fi
 
-. ${basedir}/configure-lsf-env.sh
+. ${pkglibdir}/configure-lsf-env.sh
 
 
 # configuration options
@@ -575,8 +578,8 @@ cd "$joboption_directory"
 #chmod 0755 $LRMS_JOB_SCRIPT
 
 # We make the assumption that $joboption_directory is locally available according to the requirements of any arc installation
-echo "copying  ${basedir}/change-lsf-mode.sh to ${joboption_directory}/change-lsf-mode.sh"  1>&2
-cp -pR $basedir/change-lsf-mode.sh $joboption_directory/change-lsf-mode.sh
+echo "copying  ${pkglibdir}/change-lsf-mode.sh to ${joboption_directory}/change-lsf-mode.sh"  1>&2
+cp -pR $pkglibdir/change-lsf-mode.sh $joboption_directory/change-lsf-mode.sh
 
 echo "----------------- BEGIN job script -----" 1>&2
 cat $LRMS_JOB_SCRIPT 1>&2
diff --git a/src/services/a-rex/lrms/pbs/submit-pbs-job.in b/src/services/a-rex/lrms/pbs/submit-pbs-job.in
--- a/src/services/a-rex/lrms/pbs/submit-pbs-job.in
+++ b/src/services/a-rex/lrms/pbs/submit-pbs-job.in
@@ -14,9 +14,12 @@ echo "----- starting submit_pbs_job -----" 1>&2
 joboption_lrms=PBS
 
 basedir=`dirname $0`
-basedir=`cd $basedir; pwd`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
 
-. ${basedir}/submit_common.sh
+pkglibdir="$basedir/@pkglibdir_rel_to_pkglibexecdir@"
+pkglibdir=`cd $pkglibdir > /dev/null && pwd` || exit $?
+
+. ${pkglibdir}/submit_common.sh
 
 init
 
@@ -52,13 +55,13 @@ parse_arg_file $1
 # Read queue_node_string from ARC config file
 ##############################################################
 
-if [ ! -f "$basedir/config_parser.sh" ] ; then
-    echo "$basedir/config_parser.sh not found." 1>&2
+if [ ! -f "$pkglibdir/config_parser.sh" ] ; then
+    echo "$pkglibdir/config_parser.sh not found." 1>&2
     exit 1
 fi
 
 ARC_CONFIG=${ARC_CONFIG:-/etc/arc.conf}
-. $basedir/config_parser.sh
+. $pkglibdir/config_parser.sh
 
 config_parse_file $ARC_CONFIG 1>&2 || exit $?
 config_import_section "common"
diff --git a/src/services/a-rex/lrms/sge/scan-sge-job.in b/src/services/a-rex/lrms/sge/scan-sge-job.in
--- a/src/services/a-rex/lrms/sge/scan-sge-job.in
+++ b/src/services/a-rex/lrms/sge/scan-sge-job.in
@@ -10,7 +10,10 @@
 # usage: scan_sge_job control_dir ...
 
 basedir=`dirname $0`
-basedir=`cd $basedir; pwd`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
+
+pkglibdir="$basedir/@pkglibdir_rel_to_pkglibexecdir@"
+pkglibdir=`cd $pkglibdir > /dev/null && pwd` || exit $?
 
 # Assume that gm-kick is installed in the same directory
 GMKICK=${basedir}/gm-kick
@@ -18,11 +21,11 @@ GMKICK=${basedir}/gm-kick
 ##############################################################
 # Set SGE specific environment.
 ##############################################################
-if [ ! -f "${basedir}/configure-sge-env.sh" ] ; then
-    echo "${basedir}/configure-sge-env.sh not found." 1>&2
+if [ ! -f "${pkglibdir}/configure-sge-env.sh" ] ; then
+    echo "${pkglibdir}/configure-sge-env.sh not found." 1>&2
     exit 1
 fi
-. "${basedir}/configure-sge-env.sh" 1>&2 || exit $?
+. "${pkglibdir}/configure-sge-env.sh" 1>&2 || exit $?
 
 ##############################################################
 
diff --git a/src/services/a-rex/lrms/sge/submit-sge-job.in b/src/services/a-rex/lrms/sge/submit-sge-job.in
--- a/src/services/a-rex/lrms/sge/submit-sge-job.in
+++ b/src/services/a-rex/lrms/sge/submit-sge-job.in
@@ -13,14 +13,17 @@ echo "----- starting submit_sge_job -----" 1>&2
 joboption_lrms=SGE
 
 basedir=`dirname $0`
-basedir=`cd $basedir; pwd`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
 
-if [ ! -f "${basedir}/submit_common.sh" ] ; then
-    echo "${basedir}/submit_common.sh not found." 1>&2
+pkglibdir="$basedir/@pkglibdir_rel_to_pkglibexecdir@"
+pkglibdir=`cd $pkglibdir > /dev/null && pwd` || exit $?
+
+if [ ! -f "${pkglibdir}/submit_common.sh" ] ; then
+    echo "${pkglibdir}/submit_common.sh not found." 1>&2
     exit 1
 fi
 
-. ${basedir}/submit_common.sh
+. ${pkglibdir}/submit_common.sh
 
 joboption_localtransfer='no'
 
@@ -55,12 +58,12 @@ cat $1 1>&2
 # Set SGE specific environment # needs to know $joboption_queue #
 #################################################################
 
-if [ ! -f "${basedir}/configure-sge-env.sh" ] ; then
-    echo "${basedir}/configure-sge-env.sh not found." 1>&2
+if [ ! -f "${pkglibdir}/configure-sge-env.sh" ] ; then
+    echo "${pkglibdir}/configure-sge-env.sh not found." 1>&2
     exit 1
 fi
 
-. ${basedir}/configure-sge-env.sh 1>&2 || exit $?
+. ${pkglibdir}/configure-sge-env.sh 1>&2 || exit $?
 
 ##############################################################
 # Zero stage of runtime environments
