First part of fix for bug #1151 (remove hardwired libexec location)
This could/should be used for backporting to ARC0.

diff --git a/src/services/a-rex/lrms/ll/scan-ll-job b/src/services/a-rex/lrms/ll/scan-ll-job
--- a/src/services/a-rex/lrms/ll/scan-ll-job
+++ b/src/services/a-rex/lrms/ll/scan-ll-job
@@ -4,6 +4,12 @@
 # The script is called periodically by the grid-manager.
 #
 
+basedir=`dirname $0`
+basedir=`cd $basedir; pwd`
+
+# Assume that gm-kick is installed in the same directory
+GMKICK=${basename}/gm-kick
+
 # Does the control directory exist?
 control_dir="$1"
 test -d "$control_dir" || exit 1
@@ -17,14 +23,14 @@ then
 fi
 
 # Get LoadLeveler environment
-if test -f "${ARC_LOCATION}/libexec/configure-ll-env.sh"
+if test -f "${basedir}/configure-ll-env.sh"
 then
   :
 else
-  echo "${ARC_LOCATION}/libexec/configure-ll-env.sh not found." 1>&2
+  echo "${basedir}/configure-ll-env.sh not found." 1>&2
   exit 1
 fi
-. ${ARC_LOCATION}/libexec/configure-ll-env.sh
+. "${basedir}/configure-ll-env.sh
 
 #for i in "$control_dir"/job.*.local
 find $control_dir -maxdepth 1 -type f -name job\*.local | while read i
@@ -76,17 +82,17 @@ do
     if [ "$exitcode" = "152" -o $exitcode = "24" ] ; then
 	exitcode="24"     
     	echo "$exitcode Job exceeded time limit." > "$donefile"
-        ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
+        ${GMKICK} "$statusfile"
         continue  
     fi
     # job finished and exit code is known
     echo "$exitcode Executable finished with exit code $exitcode" >> "$donefile"               
-    ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
+    ${GMKICK} "$statusfile"
     continue
   fi
   exitcode=-1
   echo "$exitcode Job finished with unknown exit code" >> "$donefile"
-  ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
+  ${GMKICK} "$statusfile"
 done
 
 sleep 60
diff --git a/src/services/a-rex/lrms/ll/submit-ll-job.in b/src/services/a-rex/lrms/ll/submit-ll-job.in
--- a/src/services/a-rex/lrms/ll/submit-ll-job.in
+++ b/src/services/a-rex/lrms/ll/submit-ll-job.in
@@ -8,23 +8,26 @@
 #
 
 echo "----- starting submit_ll_job -----" 1>&2
+
 joboption_lrms=LL
 
+basedir=`dirname $0`
+basedir=`cd $basedir; pwd`
 
 if [ -z ${ARC_LOCATION} ] ; then
     echo "ARC_LOCATION not set." 1>&2
     exit 1
 fi
-if [ ! -f "${ARC_LOCATION}/libexec/configure-ll-env.sh" ] ; then
-    echo "${ARC_LOCATION}/libexec/configure-ll-env.sh not found." 1>&2
+if [ ! -f "${basedir}/configure-ll-env.sh" ] ; then
+    echo "${basedir}/configure-ll-env.sh not found." 1>&2
     exit 1
 fi
-if [ ! -f "${ARC_LOCATION}/libexec/submit_common.sh" ] ; then
-    echo "${ARC_LOCATION}/libexec/submit_common.sh not found." 1>&2
+if [ ! -f "${basedir}/submit_common.sh" ] ; then
+    echo "${basedir}/submit_common.sh not found." 1>&2
     exit 1
 fi
-. ${ARC_LOCATION}/libexec/configure-ll-env.sh
-. ${ARC_LOCATION}/libexec/submit_common.sh
+. ${basedir}/configure-ll-env.sh
+. ${basedir}/submit_common.sh
 
 joboption_localtransfer='no'
 
diff --git a/src/services/a-rex/lrms/lsf/scan-lsf-job b/src/services/a-rex/lrms/lsf/scan-lsf-job
--- a/src/services/a-rex/lrms/lsf/scan-lsf-job
+++ b/src/services/a-rex/lrms/lsf/scan-lsf-job
@@ -8,18 +8,24 @@
 # Set variables:
 #   LSF_BIN_PATH
 
+basedir=`dirname $0`
+basedir=`cd $basedir; pwd`
+
+# Assume that gm-kick is installed in the same directory
+GMKICK=${basename}/gm-kick
+
 # "Checking NORDUGRID... "
 if [ -z ${ARC_LOCATION} ] ; then
     echo "ARC_LOCATION not set." 1>&2
     exit 1
 fi
 # "Sourcing ${ARC_LOCATION} config... " 1>&2
-if [ ! -f "${ARC_LOCATION}/libexec/configure-lsf-env.sh" ] ; then
-    echo "${ARC_LOCATION}/libexec/configure-lsf-env.sh not found." 1>&2
+if [ ! -f "${basedir}/configure-lsf-env.sh" ] ; then
+    echo "${basedir}/configure-lsf-env.sh not found." 1>&2
     exit 1
 fi
 
-. ${ARC_LOCATION}/libexec/configure-lsf-env.sh
+. ${basedir}/configure-lsf-env.sh
 umask 022
 
 STAT_USERNAME='stat -c %U'
@@ -146,7 +152,7 @@ for ctr_dir in $control_dir ; do
 	    if [ ! -z "$exitcode" ] ; then
 		# job finished and exit code is known
 		echo "$exitcode Executable finished with exit code $exitcode" > "$donefile"
-		${ARC_LOCATION}/libexec/gm-kick "$statusfile"
+		${GMKICK} "$statusfile"
 		continue
 	    fi
 	fi
@@ -163,7 +169,7 @@ for ctr_dir in $control_dir ; do
 	if [ "$counter" -gt 5 ] ; then
 	    rm -f "$countfile"
 	    echo "$exitcode Job was lost with unknown exit code" > "$donefile"
-	    ${ARC_LOCATION}/libexec/gm-kick "$statusfile"
+	    ${GMKICK} "$statusfile"
 	else
 	    echo "$counter" > "$countfile"
 	fi
diff --git a/src/services/a-rex/lrms/lsf/submit-lsf-job.in b/src/services/a-rex/lrms/lsf/submit-lsf-job.in
--- a/src/services/a-rex/lrms/lsf/submit-lsf-job.in
+++ b/src/services/a-rex/lrms/lsf/submit-lsf-job.in
@@ -9,6 +9,8 @@
 
 echo "----- starting submit_lsf_job -----" 1>&2
 
+basedir=`dirname $0`
+basedir=`cd $basedir; pwd`
 
 arg_file=$1
 
@@ -35,12 +37,12 @@ if [ -z ${ARC_LOCATION} ] ; then
     exit 1
 fi
 
-if [ ! -f "${ARC_LOCATION}/libexec/configure-lsf-env.sh" ] ; then
-    echo "${ARC_LOCATION}/libexec/configure-lsf-env.sh not found." 1>&2
+if [ ! -f "${basedir}/configure-lsf-env.sh" ] ; then
+    echo "${basedir}/configure-lsf-env.sh not found." 1>&2
     exit 1
 fi
 
-. ${ARC_LOCATION}/libexec/configure-lsf-env.sh
+. ${basedir}/configure-lsf-env.sh
 
 
 # configuration options
@@ -419,6 +421,7 @@ echo "" >> $LRMS_JOB_SCRIPT
 if [ "$joboption_localtransfer" = 'yes' ] ; then
 echo "ARC_LOCATION=\${ARC_LOCATION:-$RUNTIME_ARC_LOCATION}" >> $LRMS_JOB_SCRIPT
 echo "GLOBUS_LOCATION=\${GLOBUS_LOCATION:-$RUNTIME_GLOBUS_LOCATION}" >> $LRMS_JOB_SCRIPT
+echo "DOWNLOADER=\${DOWNLOADER:-$basedir/downloader}" >> $LRMS_JOB_SCRIPT
 cat >> $LRMS_JOB_SCRIPT <<'EOSCR'
 if [ -z "$ARC_LOCATION" ] ; then
   echo 'Variable ARC_LOCATION is not set' 1>&2
@@ -436,7 +439,7 @@ export X509_USER_KEY="${RUNTIME_CONTROL_DIR}/job.local.proxy"
 export X509_USER_CERT="${RUNTIME_CONTROL_DIR}/job.local.proxy"
 export X509_USER_PROXY="${RUNTIME_CONTROL_DIR}/job.local.proxy"
 unset X509_RUN_AS_SERVER
-$ARC_LOCATION/libexec/downloader -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
+$DOWNLOADER -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
 if [ $? -ne '0' ] ; then
   echo 'ERROR: Downloader failed.' 1>&2
   RESULT=1
@@ -478,7 +481,7 @@ while [ ! -z "${var_is_set}" ] ; do
   eval "var_value=\"\${joboption_runtime_$i}\""
   echo "  if [ -r \"\${RUNTIME_CONFIG_DIR}/${var_value}\" ] ; then" >> $LRMS_JOB_SCRIPT
   echo "    runtimeenvironments=\"\${runtimeenvironments}${var_value};\"" >> $LRMS_JOB_SCRIPT
-  echo "    source \${RUNTIME_CONFIG_DIR}/${var_value} 1 " >> $LRMS_JOB_SCRIPT
+  echo "    . \${RUNTIME_CONFIG_DIR}/${var_value} 1 " >> $LRMS_JOB_SCRIPT
   echo "  fi" >> $LRMS_JOB_SCRIPT
   i=$(( i + 1 ))
   eval "var_is_set=\${joboption_runtime_$i+yes}"
@@ -539,9 +542,10 @@ echo "fi" >> $LRMS_JOB_SCRIPT
 #  Upload output files
 ####################################################
 if [ "$joboption_localtransfer" = 'yes' ] ; then
+echo "UPLOADER=\${UPLOADER:-$basedir/uploader}" >> $LRMS_JOB_SCRIPT
 cat >> $LRMS_JOB_SCRIPT <<'EOSCR'
 if [ "$RESULT" = '0' ] ; then
-  $ARC_LOCATION/libexec/uploader -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
+  $UPLOADER -p -c 'local' "$RUNTIME_CONTROL_DIR" "$RUNTIME_JOB_DIR" 2>>${RUNTIME_CONTROL_DIR}/job.local.errors
   if [ $? -ne '0' ] ; then
     echo 'ERROR: Uploader failed.' 1>&2
     if [ "$RESULT" = '0' ] ; then RESULT=1 ; fi
@@ -584,8 +588,8 @@ cd "$joboption_directory"
 #chmod 0755 $LRMS_JOB_SCRIPT
 
 # We make the assumption that $joboption_directory is locally available according to the requirements of any arc installation
-echo "copying  ${ARC_LOCATION}/libexec/change-lsf-mode.sh to ${joboption_directory}/change-lsf-mode.sh"  1>&2
-cp -pR $ARC_LOCATION/libexec/change-lsf-mode.sh $joboption_directory/change-lsf-mode.sh
+echo "copying  ${basedir}/change-lsf-mode.sh to ${joboption_directory}/change-lsf-mode.sh"  1>&2
+cp -pR $basedir/change-lsf-mode.sh $joboption_directory/change-lsf-mode.sh
 
 echo "----------------- BEGIN job script -----" 1>&2
 cat $LRMS_JOB_SCRIPT 1>&2
diff --git a/src/services/a-rex/lrms/pbs/submit-pbs-job.in b/src/services/a-rex/lrms/pbs/submit-pbs-job.in
--- a/src/services/a-rex/lrms/pbs/submit-pbs-job.in
+++ b/src/services/a-rex/lrms/pbs/submit-pbs-job.in
@@ -9,15 +9,18 @@
 # The temporary job script is created for the submission and then removed 
 # at the end of this script. 
 
-
 echo "----- starting submit_pbs_job -----" 1>&2
+
 joboption_lrms=PBS
+
+basedir=`dirname $0`
+basedir=`cd $basedir; pwd`
 
 if [ -z ${ARC_LOCATION} ] ; then
     echo "ARC_LOCATION not set." 1>&2
     exit 1
 fi
-. ${ARC_LOCATION}/libexec/submit_common.sh
+. ${basedir}/submit_common.sh
 
 init
 
@@ -53,13 +56,13 @@ parse_arg_file $1
 # Read queue_node_string from ARC config file
 ##############################################################
 
-if [ ! -f "$ARC_LOCATION/libexec/config_parser.sh" ] ; then
-    echo "$ARC_LOCATION/libexec/config_parser.sh not found." 1>&2
+if [ ! -f "$basedir/config_parser.sh" ] ; then
+    echo "$basedir/config_parser.sh not found." 1>&2
     exit 1
 fi
 
 ARC_CONFIG=${ARC_CONFIG:-/etc/arc.conf}
-. $ARC_LOCATION/libexec/config_parser.sh
+. $basedir/config_parser.sh
 
 config_parse_file $ARC_CONFIG >&2 || exit $?
 config_import_section "common"
diff --git a/src/services/a-rex/lrms/sge/scan-sge-job.in b/src/services/a-rex/lrms/sge/scan-sge-job.in
--- a/src/services/a-rex/lrms/sge/scan-sge-job.in
+++ b/src/services/a-rex/lrms/sge/scan-sge-job.in
@@ -9,17 +9,22 @@
 #
 # usage: scan_sge_job control_dir ...
 
+basedir=`dirname $0`
+basedir=`cd $basedir; pwd`
+
+# Assume that gm-kick is installed in the same directory
+GMKICK=${basename}/gm-kick
 
 ##############################################################
 # Set SGE specific environment.
 ##############################################################
 ARC_LOCATION=${ARC_LOCATION:-@arc_location@}
 
-if [ ! -f "${ARC_LOCATION}/libexec/configure-sge-env.sh" ] ; then
-    echo "${ARC_LOCATION}/libexec/configure-sge-env.sh not found." >&2
+if [ ! -f "${basedir}/configure-sge-env.sh" ] ; then
+    echo "${basedir}/configure-sge-env.sh not found." >&2
     exit 1
 fi
-source ${ARC_LOCATION}/libexec/configure-sge-env.sh >&2 || exit $?
+. ${basedir}/configure-sge-env.sh >&2 || exit $?
 
 ##############################################################
 
@@ -256,7 +261,7 @@ for ctr_dir in $control_dirs ; do
           fi # failedcode
 
           # wake up GM
-          $ARC_LOCATION/libexec/gm-kick $statusfile >> $errorsfile
+          $GMKICK $statusfile >> $errorsfile
 
           rm -f $countfile
           rm -f $diagfile_tmp $diagfile_acct
@@ -293,7 +298,7 @@ for ctr_dir in $control_dirs ; do
       rm -f "$countfile"
 
       # wake up GM
-      $ARC_LOCATION/libexec/gm-kick $statusfile >> $errorsfile
+      $GMKICK $statusfile >> $errorsfile
 
     else
       # test again for job existence, only count if not known
diff --git a/src/services/a-rex/lrms/sge/submit-sge-job.in b/src/services/a-rex/lrms/sge/submit-sge-job.in
--- a/src/services/a-rex/lrms/sge/submit-sge-job.in
+++ b/src/services/a-rex/lrms/sge/submit-sge-job.in
@@ -20,16 +20,19 @@ memory_hardlimit_ratio='1/1'
 
 joboption_lrms=SGE
 
+basedir=`dirname $0`
+basedir=`cd $basedir; pwd`
+
 if [ -z ${ARC_LOCATION} ] ; then
     echo "ARC_LOCATION not set." 1>&2
     exit 1
 fi
-if [ ! -f "${ARC_LOCATION}/libexec/submit_common.sh" ] ; then
-    echo "${ARC_LOCATION}/libexec/submit_common.sh not found." 1>&2
+if [ ! -f "${basedir}/submit_common.sh" ] ; then
+    echo "${basedir}/submit_common.sh not found." 1>&2
     exit 1
 fi
 
-. ${ARC_LOCATION}/libexec/submit_common.sh
+. ${basedir}/submit_common.sh
 
 joboption_localtransfer='no'
 
@@ -64,12 +67,12 @@ cat $1 1>&2
 # Set SGE specific environment # needs to know $joboption_queue #
 #################################################################
 
-if [ ! -f "${ARC_LOCATION}/libexec/configure-sge-env.sh" ] ; then
-    echo "${ARC_LOCATION}/libexec/configure-sge-env.sh not found." >&2
+if [ ! -f "${basedir}/configure-sge-env.sh" ] ; then
+    echo "${basedir}/configure-sge-env.sh not found." >&2
     exit 1
 fi
 
-. ${ARC_LOCATION}/libexec/configure-sge-env.sh >&2 || exit $?
+. ${basedir}/configure-sge-env.sh >&2 || exit $?
 
 ##############################################################
 # Zero stage of runtime environments
