better error message

diff --git a/src/services/a-rex/lrms/ll/submit-ll-job.in b/src/services/a-rex/lrms/ll/submit-ll-job.in
--- a/src/services/a-rex/lrms/ll/submit-ll-job.in
+++ b/src/services/a-rex/lrms/ll/submit-ll-job.in
@@ -261,7 +261,7 @@ echo "echo \"runtimeenvironments=\$runtimeenvironments\" >> \"\$RUNTIME_JOB_DIAG
 RTE_stage1
 
 if [ -z "$RUNTIME_NODE_SEES_FRONTEND" ] ; then
-  echo "Nodes detached from gridarea are not supported yet" 1>&2
+  echo "Nodes detached from gridarea are not supported when LL is used. Aborting job submit" 1>&2
   rm -f "$LRMS_JOB_SCRIPT" "$LRMS_JOB_OUT" "$LRMS_JOB_ERR"
   exit 1
 fi
diff --git a/src/services/a-rex/lrms/lsf/submit-lsf-job.in b/src/services/a-rex/lrms/lsf/submit-lsf-job.in
--- a/src/services/a-rex/lrms/lsf/submit-lsf-job.in
+++ b/src/services/a-rex/lrms/lsf/submit-lsf-job.in
@@ -265,7 +265,7 @@ RTE_stage1
 #extra checks
 
 if [ -z "$RUNTIME_NODE_SEES_FRONTEND" ] ; then
-  echo "Nodes detached from gridarea are not supported yet" 1>&2
+  echo "Nodes detached from gridarea are not supported when LSF is used. Aborting job submit" 1>&2
   rm -f "$LRMS_JOB_SCRIPT" "$LRMS_JOB_OUT" "$LRMS_JOB_ERR"
   exit 1
 fi
