port to 4.0 partial fix for bug 3196 Removal of infosys_compat option support in bdii startup scripts, needed to phase out old infoproviders

diff --git a/src/services/ldap-infosys/create-bdii-config.in b/src/services/ldap-infosys/create-bdii-config.in
--- a/src/services/ldap-infosys/create-bdii-config.in
+++ b/src/services/ldap-infosys/create-bdii-config.in
@@ -93,7 +93,6 @@ bdii_port=${CONFIG_port:-2135}
 # Using uppercase characters in bdii_bind will break infosys.
 bdii_bind="o=grid"
 
-infosys_compat=${CONFIG_infosys_compat:-"disable"}
 infosys_nordugrid=${CONFIG_infosys_nordugrid:-"enable"}
 infosys_glue12=${CONFIG_infosys_glue12:-"disable"}
 infosys_glue2_ldap=${CONFIG_infosys_glue2_ldap:-"disable"}
@@ -103,20 +102,16 @@ gm_wakeupperiod=$(config_print_option grid-manager wakeupperiod)
 gm_wakeupperiod=${gm_wakeupperiod:-120}
 bdii_archive_size=${CONFIG_bdii_archive_size:-0}
 
-if [ "x$infosys_compat" = "xenable" ]; then
-    bdii_breathe_time=${CONFIG_bdii_breathe_time:-120}
-    bdii_read_timeout=${CONFIG_bdii_read_timeout:-300}
-else
-    # The infoprovider does the waiting, no need for BDII to do it too.  Use
-    # some small timeout to protect the system in case there is a problem with
-    # the provier
-    bdii_breathe_time=${CONFIG_bdii_breathe_time:-10}
+# The infoprovider does the waiting, no need for BDII to do it too.  Use
+# some small timeout to protect the system in case there is a problem with
+# the provier
+bdii_breathe_time=${CONFIG_bdii_breathe_time:-10}
 
-    # $provider_timeout refers to a-rex's infoprovider. BDII must also include
-    # the wait time till the next info collection cycle of a-rex.
-    max_cycle=$(( $provider_timeout + $gm_wakeupperiod ))
-    bdii_read_timeout=${CONFIG_bdii_read_timeout:-$max_cycle}
-fi
+# $provider_timeout refers to a-rex's infoprovider. BDII must also include
+# the wait time till the next info collection cycle of a-rex.
+max_cycle=$(( $provider_timeout + $gm_wakeupperiod ))
+bdii_read_timeout=${CONFIG_bdii_read_timeout:-$max_cycle}
+
 bdii_delete_delay=${CONFIG_bdii_delete_delay:-0}
 
 update_pid_file=${CONFIG_bdii_update_pid_file:-$bdii_run_dir/bdii-update.pid}
@@ -140,21 +135,12 @@ chown -R ${bdii_user}: ${bdii_log_dir}
 if [ "x$infosys_nordugrid" = "xenable" ] || \
    [ "x$infosys_glue12" = "xenable" ] || \
    [ "x$infosys_glue2_ldap" = "xenable" ]; then
-    if [ "x$infosys_compat" != "xenable" ] && \
-       [ ! -f "$ARC_LOCATION/@pkgdatasubdir@/InfosysHelper.pm" ]; then
-	echo "A-REX is not installed"
-	echo "For operation without A-REX, disable publishing of cluster information"
-	echo "(infosys_nordugrid, infosys_glue12 and infosys_glue2_ldap)"
-	echo "or enable infosys_compat in configuration"
-	exit 1
-    fi
-fi
-
-if [ "x$infosys_compat" = "xenable" ]; then
-    if [ "x$infosys_glue2_ldap" = "xenable" ]; then
-	echo "GLUE2 cannot be published when infosys_compat=enable"
-	exit 1
-    fi
+   if [ ! -f "$ARC_LOCATION/@pkgdatasubdir@/InfosysHelper.pm" ]; then
+	  echo "InfosysHelper.pm not found. Is A-REX installed?"
+	  echo "For operation without A-REX, disable publishing of cluster information"
+	  echo "(infosys_nordugrid, infosys_glue12 and infosys_glue2_ldap)"
+	  exit 1
+   fi
 fi
 
 BDII_CONF=${CONFIG_bdii_conf:-${arc_runtime_config}/bdii.conf}
@@ -315,130 +301,49 @@ cat <<-EOF > $bdii_default_ldif
 
 # Create ARC ldif generator file
 
-if [ "x$infosys_compat" = "xenable" ]; then
+ldif_generator_file=${bdii_tmp_dir}/provider/arc-nordugrid-bdii-ldif
+rm -f ${ldif_generator_file}
+touch ${ldif_generator_file}
 
-    if [ "x$infosys_nordugrid" = "xenable" ]; then
+ldif_glue12_generator=${arc_runtime_config}/arc-glue-bdii-ldif
+ldif_script="$arc_runtime_config/ldif-provider.sh"
 
-	ldif_generator_file=${bdii_tmp_dir}/provider/arc-nordugrid-bdii-ldif
-	rm -f ${ldif_generator_file}
-	touch ${ldif_generator_file}
-
-	cat <<-EOF > ${ldif_generator_file}
-		#!/bin/bash
-		# This file was automatically generated by $0
-		# Do not modify
-
-		EOF
-
-	if config_match_section cluster; then
-	    (
-		config_import_section cluster
-		cachetime=${CONFIG_cachetime:-$bdii_breathe_time}
-
-		cat <<-EOF >> ${ldif_generator_file}
-			$ARC_LOCATION/@pkgdatasubdir@/cluster.pl --valid-to $cachetime --config $ARC_CONFIG --loglevel $CONFIG_provider_loglevel --dn nordugrid-cluster-name=$hostname,Mds-Vo-name=local,o=Grid 2>> "$providerlog"
-			EOF
-
-		# Create entries for all queues
-		for queue in `config_subsections queue`; do
-		    (
-			config_import_section queue/$queue
-			cachetime=${CONFIG_cachetime:-$bdii_breathe_time}
-
-			cat <<-EOF >> ${ldif_generator_file}
-				$ARC_LOCATION/@pkgdatasubdir@/qju.pl --valid-to $cachetime --config $ARC_CONFIG --loglevel $CONFIG_provider_loglevel --dn nordugrid-queue-name=$queue,nordugrid-cluster-name=$hostname,Mds-Vo-name=local,o=Grid --queue $queue 2>> "$providerlog"
-				EOF
-		    )
-		done
-	    )
-	fi
-
-	for se in `config_subsections se`; do
-	    (
-		config_import_section se/$se
-		cachetime=${CONFIG_cachetime:-$bdii_breathe_time}
-
-		cat <<-EOF >> ${ldif_generator_file}
-			$ARC_LOCATION/@pkgdatasubdir@/se.pl -valid-to $cachetime -config $ARC_CONFIG -dn nordugrid-se-name=$se:$hostname,Mds-Vo-name=local,o=Grid -se $se 2>> "$providerlog"
-			EOF
-	    )
-	done
-
-	chmod +x ${ldif_generator_file}
-
-    fi
-
-    if [ "x$infosys_glue12" = "xenable" ]; then
-
-	ldif_generator_file_ng=${bdii_tmp_dir}/provider/arc-nordugrid-bdii-ldif
-	ldif_generator_file_glue=${bdii_tmp_dir}/provider/arc-glue-bdii-ldif
-
-	rm -f ${ldif_generator_file_glue}
-	touch ${ldif_generator_file_glue}
-
-	# We use , instead of / here to allow for / in path
-	# resource_location though, can contain commas..
-	sed "s,\$LDIF_GENERATOR_FILE_NG,$ldif_generator_file_ng,g;
-	 s/\$LOC/\"$resource_location\"/g;
-	 s/\$LAT/$resource_latitude/g;
-	 s/\$LONG/$resource_longitude/g;
-	 s/\$CPUSCALINGREFERENCESI00/$cpuscalingreferencesi00/g;
-	 s/\$PROCESSOROTHERDESCRIPTION/$processorotherdescription/g;
-	 s,\$GLUESITEWEB,$gluesiteweb,g;
-	 s,\$BDIIPORT,$bdii_port,g;
-	 s,\$GLUESITEUNIQUEID,$gluesiteuniqueid,g;
-	 s,\$PROVIDE_GLUE_SITE_INFO,$provide_glue_site_info,g;
-	" $ARC_LOCATION/@pkgdatasubdir@/glue-generator.pl > ${ldif_generator_file_glue}
-
-	chmod +x ${ldif_generator_file_glue}
-
-    fi
-
-else
-
-    ldif_generator_file=${bdii_tmp_dir}/provider/arc-nordugrid-bdii-ldif
-    rm -f ${ldif_generator_file}
-    touch ${ldif_generator_file}
-
-    ldif_glue12_generator=${arc_runtime_config}/arc-glue-bdii-ldif
-    ldif_script="$arc_runtime_config/ldif-provider.sh"
-
-    cat <<-EOF > ${ldif_generator_file}
+cat <<-EOF > ${ldif_generator_file}
 	#!/usr/bin/perl
-
+	
 	# This file was automatically generated by the $0
 	# Do not modify
 	EOF
 
-    for se in `config_subsections se`; do
-	(
-	    config_import_section se/$se
-	    cachetime=${CONFIG_cachetime:-$max_cycle}
+for se in `config_subsections se`; do
+(
+    config_import_section se/$se
+    cachetime=${CONFIG_cachetime:-$max_cycle}
 
-	    cat <<-EOF >> ${ldif_generator_file}
-
-		BEGIN {
-		    print "\n";
-		    system('$ARC_LOCATION/@pkgdatasubdir@/se.pl -valid-to $cachetime -config $ARC_CONFIG -dn nordugrid-se-name=$se:$hostname,Mds-Vo-name=local,o=Grid -se $se 2>> "$providerlog"');
-		}
-		EOF
-	)
-    done
-
-    # NG and GLUE2 come directly from a-rex infoprovider
     cat <<-EOF >> ${ldif_generator_file}
+	
+	BEGIN {
+	    print "\n";
+	    system('$ARC_LOCATION/@pkgdatasubdir@/se.pl -valid-to $cachetime -config $ARC_CONFIG -dn nordugrid-se-name=$se:$hostname,Mds-Vo-name=local,o=Grid -se $se 2>> "$providerlog"');
+	}
+	EOF
+)
+done
 
+# NG and GLUE2 come directly from a-rex infoprovider
+cat <<-EOF >> ${ldif_generator_file}
+	
 	BEGIN { unshift @INC, '$ARC_LOCATION/@pkgdatasubdir@'; }
 	use InfosysHelper;
 	exit 1 unless InfosysHelper::ldifIsReady('$arc_runtime_config', '$max_cycle');
 	EOF
 
-    if [ "x$infosys_nordugrid" = "xenable" ] || \
-       [ "x$infosys_glue2_ldap" = "xenable" ]; then
-	echo "system('$ldif_script');" >> ${ldif_generator_file}
-    fi
+if [ "x$infosys_nordugrid" = "xenable" ] || \
+   [ "x$infosys_glue2_ldap" = "xenable" ]; then
+   echo "system('$ldif_script');" >> ${ldif_generator_file}
+fi
 
-    if [ "x$infosys_glue12" = "xenable" ]; then
+if [ "x$infosys_glue12" = "xenable" ]; then
 	ldif_generator_file_ng=${bdii_tmp_dir}/provider/arc-nordugrid-bdii-ldif
 	ldif_generator_file_glue=${bdii_tmp_dir}/provider/arc-glue-bdii-ldif
 
@@ -462,11 +367,10 @@ else
 	chmod +x ${ldif_generator_file_glue}
 
 	echo "system('$ldif_glue12_generator');" >> ${ldif_generator_file}
-    fi
-
-    chmod +x ${ldif_generator_file}
-
 fi
+
+chmod +x ${ldif_generator_file}
+
 
 # Site BDII
 
