Updated glue-generator to generate proper output for a resource bdii

diff --git a/src/services/ldap-infosys/grid-infosys-bdii5.in b/src/services/ldap-infosys/grid-infosys-bdii5.in
--- a/src/services/ldap-infosys/grid-infosys-bdii5.in
+++ b/src/services/ldap-infosys/grid-infosys-bdii5.in
@@ -156,6 +156,7 @@ if [ -f /lib/lsb/init-functions ]; then
     . /lib/lsb/init-functions
 else
     echo "Error: Cannot source /lib/lsb/init-functions"
+    exit 1
 fi
 
 # sysconfig files
@@ -452,11 +453,14 @@ fi
 resource_location=""
 resource_latitude=""
 resource_longitude=""
+cpuscalingreferencesi00=""
+processorotherdescription=""
+gluesiteweb=""
 
 if [ "x$infosys_glue12" = "xenable" ]; then
 
     if ! config_match_section infosys/glue12 ; then
-        eval log_failure_msg "Missing infosys/glue12 block"
+        eval log_failure_msg "Error: infosys_glue12 is set to enable, but infosys/glue12 block is missing."
         do_exit_start 1
     fi
 
@@ -464,6 +468,9 @@ if [ "x$infosys_glue12" = "xenable" ]; then
     resource_location=${CONFIG_resource_location}
     resource_latitude=${CONFIG_resource_latitude}
     resource_longitude=${CONFIG_resource_longitude}
+    cpuscalingreferencesi00=${CONFIG_cpu_scaling_reference_si00}
+    processorotherdescription=${CONFIG_processor_other_description}
+    gluesiteweb=${CONFIG_glue_site_web}
 
     if [ "x$resource_location" = "x" ]; then
         eval log_failure_msg "If infosys_glue12 is enabled, then resource_location must be set."
@@ -483,6 +490,26 @@ if [ "x$infosys_glue12" = "xenable" ]; then
         eval log_failure_msg "for example: '12.41670'"
         exit 1
     fi
+    if [ "x$cpuscalingreferencesi00" = "x" ]; then
+        log_failure_msg "If infosys_glue12 is enabled, then cpu_scaling_reference_si00 must be set."
+        log_failure_msg "It should be set to the SI00 value,"
+        log_failure_msg "for example: '2400'"
+        exit 1
+    fi
+    if [ "x$processorotherdescription" = "x" ]; then
+        log_failure_msg "If infosys_glue12 is enabled, then processor_other_description must be set."
+        log_failure_msg "It should be set to a value like in the example,where cores is the average number"
+        log_failure_msg "of cores in the machine"
+        log_failure_msg "for example: 'Cores=3,Benchmark=9.8-HEP-SPEC06'"
+        exit 1
+    fi
+    if [ "x$gluesiteweb" = "x" ]; then
+        log_failure_msg "If infosys_glue12 is enabled, then gluesiteweb must be set."
+        log_failure_msg "It should be set to a url for the website belonging to the institution holding the resource,"
+        log_failure_msg "for example: 'http://www.ndgf.org'"
+        exit 1
+    fi
+
 fi
 
 # bdii.conf is put into nordugrid runtime directory
@@ -653,10 +680,10 @@ create_default_ldif () {
 	print "Mds-validto: " . strftime("%Y%m%d%H%M%SZ\n", gmtime(time() + 3600));
 	print "\n";
 
-	print "dn: Mds-Vo-name=glue12,o=Grid\n";
+	print "dn: Mds-Vo-name=resource,o=Grid\n";
 	print "objectClass: Mds\n";
 	print "objectClass: MdsVo\n";
-	print "Mds-Vo-name: glue12\n";
+	print "Mds-Vo-name: resource\n";
 	print "Mds-validfrom: " . strftime("%Y%m%d%H%M%SZ\n", gmtime());
 	print "Mds-validto: " . strftime("%Y%m%d%H%M%SZ\n", gmtime(time() + 3600));
 	EOF
@@ -885,9 +912,17 @@ create_glue_ldif_generator () {
     rm -f ${ldif_generator_file_glue}
     touch ${ldif_generator_file_glue}
     std_header ${ldif_generator_file_glue}
-    # We use , instead of / here to allow for / in path..
-    sed "s,\$ldif_generator_file_ng,$ldif_generator_file_ng,g;s,\$bdii_tmp_dir,$bdii_tmp_dir,g" $ARC_LOCATION/@pkglibsubdir@/glue-generator.pl > ${ldif_generator_file_glue}
-#    sed "s,\$ldif_generator_file_ng,$ldif_generator_file_ng,g;s,\$bdii_tmp_dir,$bdii_tmp_dir,g" $ARC_LOCATION/@pkglibsubdir@/glue-generator.pl > ${ldif_generator_file_glue}
+
+    # We use , instead of / here to allow for / in path, resource_location though, can contain commas..
+    sed "s,\$LDIF_GENERATOR_FILE_NG,$ldif_generator_file_ng,g;
+         s/\$LOC/\"$resource_location\"/g;
+         s/\$LAT/$resource_latitude/g;
+         s/\$LONG/$resource_longitude/g;
+         s/\$CPUSCALINGREFERENCESI00/$cpuscalingreferencesi00/g;
+         s/\$PROCESSOROTHERDESCRIPTION/$processorotherdescription/g;
+         s/\$GLUESITEWEB/$gluesiteweb/g;
+        " $NORDUGRID_LOCATION/@pkgdatadir@/glue-generator.pl > ${ldif_generator_file_glue}
+
 
     chmod +x ${ldif_generator_file_glue}
 }
@@ -949,12 +984,6 @@ create_bdii_config_files () {
 
     # Create arc-glue-bdii-ldif, generates ldif-files for glue schema
     if [ "x$infosys_glue12" = "xenable" ]; then
-        cat <<-EOF > ${bdii_tmp_dir}/ndgf-coord.def
-	loc: $resource_location
-	lat: $resource_latitude
-	long: $resource_longitude
-	EOF
-
         # Call with create_glue_ldif_generator bdii_tmp_dir ldif_generator_file_ng ldif_generator_file_glue
         create_glue_ldif_generator $bdii_tmp_dir ${bdii_tmp_dir}/provider/arc-nordugrid-bdii-ldif ${bdii_tmp_dir}/provider/arc-glue-bdii-ldif
     fi
