- fixed issues in bug 2764, using mktemp and other recommendations from Anders.

diff --git a/src/services/ldap-infosys/grid-infosys.in b/src/services/ldap-infosys/grid-infosys.in
--- a/src/services/ldap-infosys/grid-infosys.in
+++ b/src/services/ldap-infosys/grid-infosys.in
@@ -285,6 +285,8 @@ if [ ! -e $bdii_update_cmd ]; then
     exit 1
 fi
 
+bdii_debug_level=${CONFIG_bdii_debug_level:-ERROR}
+
 bdii_tmp_dir=${CONFIG_bdii_tmp_dir:-/var/tmp/arc/bdii}
 if grep -q BDII_PID_FILE $bdii_update_cmd ; then
 bdii_var_dir=${CONFIG_bdii_var_dir:-/var/lib/arc/bdii}
@@ -584,7 +586,7 @@ create_bdii_conf () {
     cat <<-EOF >> ${BDII_CONF}
 	BDII_LOG_FILE=$bdii_log_file
 	BDII_PID_FILE=$update_pid_file
-	BDII_LOG_LEVEL=ERROR
+	BDII_LOG_LEVEL=$bdii_debug_level
 	BDII_LDIF_DIR=$bdii_ldif_dir
 	BDII_PROVIDER_DIR=$bdii_provider_dir
 	BDII_PLUGIN_DIR=$bdii_plugin_dir
@@ -1257,40 +1259,51 @@ start () {
     chown $bdii_user:$bdii_user $bdii_log_file
     
     ## workaround for BDII DB_CONFIG cachesize bigger than actual memory
-    memsize=$(grep MemTotal /proc/meminfo | awk '{print $2}')000
-    bdii_default_set_cachesize_gb=`grep set_cachesize ${bdii_db_config} | awk '{print $2}'`
-    bdii_default_set_cachesize_kb=`grep set_cachesize ${bdii_db_config} | awk '{print $3}'`
-    if [ $bdii_default_set_cachesize_gb -ne '0' ]; then
-        bdii_default_set_cachesize_gb=${bdii_default_set_cachesize_gb}000000000
-        let sum=${bdii_default_set_cachesize_gb}+${bdii_default_set_cachesize_kb}
-        bdii_default_set_cachesize_kb=$sum
+    ## Not applied if set_cachesize is missing
+    bdii_cachesize_line=`egrep '^[[:space:]]*'set_cachesize ${bdii_db_config}`
+    if [ -n "${bdii_cachesize_line}" ]; then
+        if [ -e /proc/meminfo ]; then
+          memsize=$(grep MemTotal /proc/meminfo | awk '{print $2}')000
+          bdii_default_set_cachesize_kb=$memsize;
+          bdii_default_set_cachesize_gb=`echo ${bdii_cachesize_line} | awk '{print $2}'`
+          bdii_default_set_cachesize_kb=`echo ${bdii_cachesize_line} | awk '{print $3}'`
+          if [ $bdii_default_set_cachesize_gb != '0' ]; then
+              bdii_default_set_cachesize_gb=${bdii_default_set_cachesize_gb}000000000
+              let sum=${bdii_default_set_cachesize_gb}+${bdii_default_set_cachesize_kb}
+              bdii_default_set_cachesize_kb=$sum
+          fi
+          if [ $bdii_default_set_cachesize_kb -ge $memsize ]; then
+             log_warning_msg "The system does not fulfill BDII optimal memory requirements. ARC will try to fix it anyway..."
+             let a=$memsize/16
+             cachesize=$a
+             TEMPBDIIDBCONFIG=`mktemp -q /tmp/DB_CONFIG.XXXXXX`
+             if [ $? -ne 0 ]; then
+               log_warning_msg "Can't create workaround DB_CONFIG temp file. If slapd doesn't start,"
+               log_warning_msg "please manually set set_cachesize parameter in ${bdii_db_config}"
+             else 
+               sed "s/^set_cachesize.*$/set_cachesize 0 $cachesize 1/" $bdii_db_config > $TEMPBDIIDBCONFIG
+               bdii_db_config=${TEMPBDIIDBCONFIG}
+               log_warning_msg "DB_CONFIG set_cachesize is now :  0 $cachesize 1"
+             fi
+          fi
+        else 
+          log_warning_msg "/proc/meminfo does not exist. Cannot apply BDII memory workaround."
+          log_warning_msg "slapd might fail to start."
+        fi
     fi
-
-    if [ $bdii_default_set_cachesize_kb -gt $memsize ]; then
-            log_warning_msg "The system doesn't fulfill BDII optimal memory requirements. ARC will try to fix it anyway..."
-            let a=$memsize/16
-            cachesize=$a
-            sed "s/^set_cachesize.*$/set_cachesize 0 $cachesize 1/" $bdii_db_config > /tmp/DB_CONFIG
-            if [[ ! -a /tmp/DB_CONFIG ]]; then
-                log_failure_msg "/tmp/DB_CONFIG couldn't be written. Ldap infosys cannot be started. Please manually set set_cachesize parameter in ${bdii_db_config} to a value that is lesser than the system physical memory."
-                exit 1
-            fi
-            bdii_db_config='/tmp/DB_CONFIG'
-            log_warning_msg "DB_CONFIG set_cachesize is now :  0 $cachesize 1"
-    fi
-    ## end of BDII low memory workaround
+    ## end of BDII set_cachesize workaround
     
     # copy BDII DB_CONFIG in ARC locations
-    $RUNUSER -s "$USERSHELL" -c "cp ${bdii_db_config} ${bdii_var_dir}/db/arc" $bdii_user
-    $RUNUSER -s "$USERSHELL" -c "cp ${bdii_db_config} ${bdii_var_dir}/db/glue2" $bdii_user
-    $RUNUSER -s "$USERSHELL" -c "cp ${bdii_db_config} ${bdii_var_dir}/db/stats" $bdii_user
+    $RUNUSER -s "$USERSHELL" -c "cp ${bdii_db_config} ${bdii_var_dir}/db/arc/DB_CONFIG" $bdii_user
+    $RUNUSER -s "$USERSHELL" -c "cp ${bdii_db_config} ${bdii_var_dir}/db/glue2/DB_CONFIG" $bdii_user
+    $RUNUSER -s "$USERSHELL" -c "cp ${bdii_db_config} ${bdii_var_dir}/db/stats/DB_CONFIG" $bdii_user
     #Need to remove / from mkpasswd, otherwise sed will break.
     pass=`/usr/bin/mkpasswd -s 0 2> /dev/null` || pass=$RANDOM$RANDOM
     pass=${pass//\//x}
 
     # if the BDII low memory workaround has been applied, remove dir from tmp
-    if [[ -a /tmp/DB_CONFIG ]]; then
-        rm /tmp/DB_CONFIG
+    if [[ -a $TEMPBDIIDBCONFIG ]]; then
+        rm -f $TEMPBDIIDBCONFIG
     fi
 
     if [ ! -f ${bdii_slapd_conf} ]; then
