Move architecture independent stuff out of libdir and libexecdir

diff --git a/src/services/ldap-infosys/grid-infosys-bdii5.in b/src/services/ldap-infosys/grid-infosys-bdii5.in
--- a/src/services/ldap-infosys/grid-infosys-bdii5.in
+++ b/src/services/ldap-infosys/grid-infosys-bdii5.in
@@ -171,10 +171,10 @@ fi
 export ARC_LOCATION
 
 # source the config parsing routines
-if [ -r "$ARC_LOCATION/@pkglibsubdir@/config_parser_compat.sh" ]; then
-    . $ARC_LOCATION/@pkglibsubdir@/config_parser_compat.sh || exit $?
+if [ -r "$ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh" ]; then
+    . $ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh || exit $?
 else
-    eval log_failure_msg "Error: could not find $ARC_LOCATION/@pkglibsubdir@/config_parser_compat.sh"
+    eval log_failure_msg "Error: could not find $ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh"
     exit 1
 fi
 
@@ -214,7 +214,7 @@ config_set_defaults () {
 }
 
 # Read arc.conf
-export pkglibdir=$ARC_LOCATION/@pkglibsubdir@
+export pkgdatadir=$ARC_LOCATION/@pkgdatasubdir@
 config_parse_file $ARC_CONFIG || exit $?
 
 # Check for infosys-block
@@ -418,7 +418,7 @@ fi
 
 # If the new code path is selected...
 if [ "x$infosys_compat" != "xenable" ]; then
-    if [ ! -f "$pkglibdir/InfosysHelper.pm" ]; then
+    if [ ! -f "$pkgdatadir/InfosysHelper.pm" ]; then
         eval log_failure_msg "A-REX is not installed. For operation without A-REX, set infosys_compat=enable"
         exit 1
     fi
@@ -461,9 +461,9 @@ fi
 if [ $(grep -Ec "${bdii_database}_db_init|${bdii_database}_back_db_init" "$slapd_cmd") -eq 0 ]; then
 
     # Guess a likely directory for ldap modules
-    ldaplib=$(find /usr/lib/ -name "back_${bdii_database}.so" -printf "%h/\n" 2>/dev/null)
+    ldaplib=$(find /usr/lib -name "back_${bdii_database}.so" -printf "%h/\n" 2>/dev/null)
     if [ "x" = "x$ldaplib" ]; then
-        eval log_failure_msg "Error, could not find ldap libraries under /usr/lib/"
+        eval log_failure_msg "Error, could not find ldap libraries under /usr/lib"
         exit 1
     fi
 
@@ -477,9 +477,9 @@ if [ "`config_subsections infosys/index`" ]; then
     if [ $(grep -Ec "shell_db_init|shell_back_db_init" "$slapd_cmd") -eq 0 ]; then
 
         # Guess a likely directory for ldap modules
-        ldaplib=${ldaplib:-$(find /usr/lib/ -name "back_shell.so" -printf "%h/\n" 2>/dev/null)}
+        ldaplib=${ldaplib:-$(find /usr/lib -name "back_shell.so" -printf "%h/\n" 2>/dev/null)}
         if [ "x" = "x$ldaplib" ]; then
-            eval log_failure_msg "Error, could not find ldap libraries under /usr/lib/"
+            eval log_failure_msg "Error, could not find ldap libraries under /usr/lib"
             exit 1
         fi
 
@@ -803,7 +803,7 @@ create_arc_ldif_generator_compat () {
             cachetime=${CONFIG_cachetime:-$bdii_breathe_time}
 
             cat <<-EOF >> ${ldif_generator_file}
-		$ARC_LOCATION/@pkglibexecsubdir@/cluster.pl --valid-to $cachetime --config $ARC_CONFIG --loglevel $CONFIG_provider_loglevel --dn nordugrid-cluster-name=$hostname,Mds-Vo-name=local,o=Grid 2>> "$providerlog"
+		$ARC_LOCATION/@pkgdatasubdir@/cluster.pl --valid-to $cachetime --config $ARC_CONFIG --loglevel $CONFIG_provider_loglevel --dn nordugrid-cluster-name=$hostname,Mds-Vo-name=local,o=Grid 2>> "$providerlog"
 		EOF
 
             # Create entries for all queues
@@ -813,7 +813,7 @@ create_arc_ldif_generator_compat () {
                     cachetime=${CONFIG_cachetime:-$bdii_breathe_time}
 
                     cat <<-EOF >> ${ldif_generator_file}
-			$ARC_LOCATION/@pkglibexecsubdir@/qju.pl --valid-to $cachetime --config $ARC_CONFIG --loglevel $CONFIG_provider_loglevel --dn nordugrid-queue-name=$queue,nordugrid-cluster-name=$hostname,Mds-Vo-name=local,o=Grid --queue $queue 2>> "$providerlog"
+			$ARC_LOCATION/@pkgdatasubdir@/qju.pl --valid-to $cachetime --config $ARC_CONFIG --loglevel $CONFIG_provider_loglevel --dn nordugrid-queue-name=$queue,nordugrid-cluster-name=$hostname,Mds-Vo-name=local,o=Grid --queue $queue 2>> "$providerlog"
 			EOF
                 )
             done
@@ -834,7 +834,7 @@ create_arc_ldif_generator_compat () {
             cachetime=${CONFIG_cachetime:-$bdii_breathe_time}
 
             cat <<-EOF >> ${ldif_generator_file}
-		$ARC_LOCATION/@pkglibexecsubdir@/se.pl -valid-to $cachetime -config $ARC_CONFIG -dn nordugrid-se-name=$se:$hostname,Mds-Vo-name=local,o=Grid -se $se 2>> "$providerlog"
+		$ARC_LOCATION/@pkgdatasubdir@/se.pl -valid-to $cachetime -config $ARC_CONFIG -dn nordugrid-se-name=$se:$hostname,Mds-Vo-name=local,o=Grid -se $se 2>> "$providerlog"
 		EOF
         )
     done
@@ -884,7 +884,7 @@ create_arc_ldif_generator () {
             cat <<-EOF >> ${ldif_generator_file}
 			BEGIN {
 			    print "\n";
-			    system('$ARC_LOCATION/@pkglibexecsubdir@/se.pl -valid-to $cachetime -config $ARC_CONFIG -dn nordugrid-se-name=$se:$hostname,Mds-Vo-name=local,o=Grid -se $se 2>> "$providerlog"');
+			    system('$ARC_LOCATION/@pkgdatasubdir@/se.pl -valid-to $cachetime -config $ARC_CONFIG -dn nordugrid-se-name=$se:$hostname,Mds-Vo-name=local,o=Grid -se $se 2>> "$providerlog"');
 			}
 			EOF
         )
@@ -893,7 +893,7 @@ create_arc_ldif_generator () {
     # NG and GLUE2 come directly from a-rex infoprovider
     cat <<-EOF >> ${ldif_generator_file}
 
-	BEGIN { unshift @INC, '$pkglibdir'; }
+	BEGIN { unshift @INC, '$pkgdatadir'; }
 	use InfosysHelper;
 	exit 1 unless InfosysHelper::ldifIsReady('$arc_runtime_config', '$max_cycle');
 	EOF
@@ -1072,8 +1072,8 @@ create_glue_ldif_generator () {
          s,\$GLUESITEWEB,$gluesiteweb,g;
          s,\$BDIIPORT,$bdii_port,g;
          s,\$GLUESITEUNIQUEID,$gluesiteuniqueid,g;
-	 s,\$PROVIDE_GLUE_SITE_INFO,$provide_glue_site_info,g;
-        " $ARC_LOCATION/@pkglibsubdir@/glue-generator.pl > ${ldif_generator_file_glue}
+         s,\$PROVIDE_GLUE_SITE_INFO,$provide_glue_site_info,g;
+        " $ARC_LOCATION/@pkgdatasubdir@/glue-generator.pl > ${ldif_generator_file_glue}
 
 
     chmod +x ${ldif_generator_file_glue}
@@ -1163,7 +1163,7 @@ create_bdii_config_files () {
         echo "$unique_id $url" > "$site_config"
       # LOOP END 
       # Create script
-      printf "#!/bin/sh\n/$ARC_LOCATION/@pkglibsubdir@/glite-info-provider-ldap -m \"$site_bdii\" -c $site_config\n" > $site_provider
+      printf "#!/bin/sh\n/$ARC_LOCATION/@pkgdatasubdir@/glite-info-provider-ldap -m \"$site_bdii\" -c $site_config\n" > $site_provider
       chmod +x $site_provider
     done
 
@@ -1274,7 +1274,7 @@ start () {
 
     # If index-server configured, start it
     if [ "`config_subsections infosys/index`" ]; then
-        $giis_location/sbin/arc-infoindex-server -c $ARC_CONFIG -f $giis_fifo
+        ${giis_location}/sbin/arc-infoindex-server -c $ARC_CONFIG -f $giis_fifo
     fi
 
     # Start BDII
@@ -1284,9 +1284,17 @@ start () {
     echo -n "Starting $prog: "
 
     if [ "`config_subsections infosys/index`" ]; then
-        #The -d 0 is important for the GIIS to ensure that the binary doesn't fork.
-        ARC_LDAPLIB_SHELL=$ldaplib/back_shell.so \
-            LD_PRELOAD=${giis_location}/@pkglibsubdir@/arc-infoindex-slapd-wrapper.so \
+        if [ -r ${giis_location}/lib64/arc/arc-infoindex-slapd-wrapper.so ] ; then
+            pkglibdir=${giis_location}/lib64/arc
+        elif [ -r ${giis_location}/lib/arc/arc-infoindex-slapd-wrapper.so ] ; then
+            pkglibdir=${giis_location}/lib/arc
+        else
+            error_echo "Error, could not find infoindex slapd wrapper"
+            exit 1
+        fi
+        # The -d 0 is important for the GIIS to ensure that the binary doesn't fork.
+        ARC_LDAPLIB_SHELL=${ldaplib}/back_shell.so \
+            LD_PRELOAD=${pkglibdir}/arc-infoindex-slapd-wrapper.so \
             ${slapd_cmd} -d 0 -f ${bdii_slapd_conf} -h ldap://${slapd_hostnamebind}:${bdii_port} \
             -u ${bdii_user} </dev/null 1>/dev/null 2>/dev/null &
     else
@@ -1344,7 +1352,7 @@ start () {
 
     # Info registration
     if [ "x$infosys_nordugrid" = "xenable" ]; then
-        $ARC_LOCATION/@pkglibexecsubdir@/grid-info-soft-register -log $registrationlog -f $arc_runtime_config/grid-info-resource-register.conf -p `cat /var/run/bdii-update.pid` 1>/dev/null 2>/dev/null &
+        $ARC_LOCATION/@pkgdatasubdir@/grid-info-soft-register -log $registrationlog -f $arc_runtime_config/grid-info-resource-register.conf -p `cat /var/run/bdii-update.pid` 1>/dev/null 2>/dev/null &
     fi
 
     success
