Various bug fixes to new infosys start-up scripts

diff --git a/src/services/ldap-infosys/nordugrid-arc-bdii.in b/src/services/ldap-infosys/nordugrid-arc-bdii.in
--- a/src/services/ldap-infosys/nordugrid-arc-bdii.in
+++ b/src/services/ldap-infosys/nordugrid-arc-bdii.in
@@ -22,7 +22,7 @@
 ### END INIT INFO
 
 # Helper functions
-if [ -f /etc/init.d/functions ]; then
+if [ -r /etc/init.d/functions ]; then
     . /etc/init.d/functions
     log_success_msg() {
 	echo -n "$@"
@@ -39,7 +39,7 @@ if [ -f /etc/init.d/functions ]; then
 	failure "$@"
 	echo
     }
-elif [ -f /lib/lsb/init-functions ]; then
+elif [ -r /lib/lsb/init-functions ]; then
     . /lib/lsb/init-functions
 else
     echo "Error: Cannot source neither init.d nor lsb functions"
@@ -63,10 +63,13 @@ elif [ -r /etc/default/$prog ]; then
 fi
 
 if [ "x$RUN" != "xyes" ]; then
-    echo "$prog disabled, please adjust the configuration to your needs "
-    echo "and then set RUN to 'yes' in /etc/default/$prog to enable it."
+    log_warning_msg "$prog disabled, please adjust the configuration to your"
+    log_warning_msg "needs and then set RUN to 'yes' in /etc/default/$prog to enable it."
     exit 0
 fi
+
+[ -n "$ARC_LOCATION" ] && export ARC_LOCATION
+[ -n "$ARC_CONFIG" ]   && export ARC_CONFIG
 
 ARC_LOCATION=${ARC_LOCATION:-@prefix@}
 if [ ! -d "$ARC_LOCATION" ]; then
@@ -84,7 +87,6 @@ fi
 
 ARC_CONFIG=${ARC_CONFIG:-/etc/arc.conf}
 if [ ! -r "$ARC_CONFIG" ]; then
-    echo "ARC configuration file arc.conf was not found (usually /etc/arc.conf)"
     log_failure_msg "arc.conf was not found. If this file is in a non-standard place,"
     log_failure_msg "  it can be set with the ARC_CONFIG environment variable"
     exit 1
@@ -113,8 +115,8 @@ debug=${CONFIG_debug:-$debug}
 
 ldap_user=`getent passwd | grep ldap | sed 's/\([az]*\):.*/\1/g'`
 if [ ! "xldap" = "x$ldap_user" ] && [ ! "xopenldap" = "x$ldap_user" ]; then
-    debug_echo "Warning, could not find ldap or openldap user"
-    debug_echo "resorting to using the root user."
+    log_warning_msg "Warning, could not find ldap or openldap user"
+    log_warning_msg "resorting to using the root user."
     ldap_user=root
 fi
 bdii_user=${CONFIG_user:-$ldap_user}
@@ -123,7 +125,7 @@ bdii_user=${CONFIG_user:-$ldap_user}
 hostname_f=$(hostname -f)
 hostname=${CONFIG_hostname:-$hostname_f}
 
-# Use this command to change user, needs to be paired with -s "/bin/sh" to handle users without a shell
+# Use this command to change user
 if [ -x /sbin/runuser ]; then
     RUNUSER=runuser
 else
@@ -133,10 +135,9 @@ fi
 # If missing, we have a problem
 USERSHELL=${USERSHELL:-"/bin/sh"}
 if [ ! -x ${USERSHELL} ]; then
-    error_echo "Could not find /bin/sh"
+    log_failure_msg "Could not find /bin/sh"
     exit 1
 fi
-
 
 bdii_location=${CONFIG_bdii_location:-/usr}
 giis_location=${CONFIG_giis_location:-$ARC_LOCATION}
@@ -180,14 +181,15 @@ update_pid_file=${CONFIG_bdii_update_pid_file:-$bdii_run_dir/bdii-update.pid}
 
 # Debian does not have /var/lock/subsys
 if [ -d /var/lock/subsys ]; then
-    update_lock_file=${update_lock_file:-/var/lock/subsys/arc-bdii-update}
+    update_lock_file=${update_lock_file:-/var/lock/subsys/$prog}
 else
-    update_lock_file=${update_lock_file:-/var/lock/arc-bdii-update}
+    update_lock_file=${update_lock_file:-/var/lock/$prog}
 fi
 
 chown ${bdii_user} ${bdii_log_dir}
 
 arc_runtime_config="/var/run/arc/infosys"
+BDII_CONF=${CONFIG_bdii_conf:-${arc_runtime_config}/bdii.conf}
 
 start () {
     if [ -r "${update_lock_file}" ]; then
@@ -205,71 +207,58 @@ start () {
     $RUNUSER -s "$USERSHELL" -c "${bdii_update_cmd} -c ${BDII_CONF} -d" ${bdii_user}
     touch ${update_lock_file}
 
-    if [ ! -f ${update_pid_file} ]; then
+    if [ ! -r ${update_pid_file} ]; then
 	sleep 2
     fi
-    if [ -f ${update_pid_file} ]; then
-	ps $(cat ${update_pid_file}) >/dev/null 2>&1
-	RETVAL=$?
-    else
-	log_failure_msg
-	exit 1
-    fi
-
-    if [ ${RETVAL} -gt 0 ]; then
-	log_failure_msg
-	log_failure_msg "$prog update process failed to start"
+    if [ ! -r ${update_pid_file} ]; then
+	log_failure_msg "$prog failed to start"
 	rm -f ${update_lock_file}
 	exit 1
     else
-	touch $lockfile
+	touch ${update_lock_file}
 	RETVAL=0
     fi
 
-    log_success_msg
+    log_success_msg "$prog started"
 }
 
 stop () {
-    # Stop GRIS
+    if [ ! -r "${update_lock_file}" ]; then
+	log_success_msg "$prog already stopped"
+	RETVAL=0
+	return ${RETVAL}
+    fi
 
-    if [ ! -f "${update_lock_file}" ]; then
-	echo -n "Stopping $prog: "
-	result=$($0 status)
-	if [ $? -gt 0 ]; then
-	    log_failure_msg
-	    echo ${result} 1>&2
-	    return 1
-	else
-	    log_success_msg "$prog already stopped"
-	    return 0
+    if [ -r "${update_pid_file}" ]; then
+	update_pid=$(cat ${update_pid_file})
+	ps ${update_pid} >/dev/null 2>&1
+	if [ ! $? = 0 ]; then
+	    log_failure_msg "$prog pid file exists but the process died"
+	    RETVAL=1
+	    return ${RETVAL}
 	fi
+    else
+	log_failure_msg "$prog process has no pid file"
+	RETVAL=1
+	return ${RETVAL}
     fi
 
     killall -u ${bdii_user} -15 arc-nordugrid-bdii-ldif 2>/dev/null
 
-    if [ -f "${update_pid_file}" ]; then
-	update_pid=$(cat ${update_pid_file})
-    else
-	log_failure_msg "$prog update process has no pid-file"
-	return 1
-    fi
-
     if [ -n "${update_pid}" ]; then
-	$RUNUSER -s "$USERSHELL" -c "kill -15 ${update_pid} 2>/dev/null" ${bdii_user}
-
+	kill -15 ${update_pid} 2>/dev/null
 	ps ${update_pid} >/dev/null 2>&1
 	if [ $? = 0 ]; then
 	    sleep 2
 	    ps ${update_pid} >/dev/null 2>&1
 	    if [ $? = 0 ]; then
-		$RUNUSER -s "$USERSHELL" -c "kill -9 ${update_pid} 2>/dev/null" ${bdii_user}
+		kill -9 ${update_pid} 2>/dev/null
 		sleep 2
 		ps ${update_pid} >/dev/null 2>&1
 		if [ $? = 0 ]; then
 		    RETVAL=1
 		fi
 	    fi
-
 	fi
     fi
 
@@ -277,7 +266,7 @@ stop () {
 	rm -f ${update_pid_file}
 	rm -f ${update_lock_file}
     else
-	log_failure_msg "Could not kill $prog update process with pid ${update_pid}"
+	log_failure_msg "Could not kill $prog with pid ${update_pid}"
     fi
 
     # Clean up
@@ -287,56 +276,35 @@ stop () {
 	log_failure_msg
 	return 1
     else
-	# lockfile is to make sure that bdii gets a clean shutdown with system
-	rm -f $lockfile
+	rm -f ${update_lock_file}
+	log_success_msg "$prog stopped"
     fi
 
-    log_success_msg
     return ${RETVAL}
 }
 
 status ()  {
     if [ ! -f "${update_lock_file}" ]; then
-	log_success_msg "BDII Stopped"
+	log_success_msg "$prog is stopped"
 	RETVAL=3
 	return ${RETVAL}
     fi
 
-    if [ -f ${slapd_pid_file} ]; then
-	ps $(cat ${slapd_pid_file}) >/dev/null 2>&1
-	if [ ! $? = 0 ]; then
-	    log_failure_msg "slapd pid file exists: ${slapd_pid_file} but the process died"
-	    RETVAL=1
-	    return ${RETVAL}
-	fi
-    else
-	log_failure_msg "slapd lock file: ${slapd_lock_file} and/or"
-	log_failure_msg "bdii-update lock file: ${update_lock_file} exists but"
-	log_failure_msg "slapd pid file: ${slapd_pid_file} does not exist."
-	log_failure_msg "Maybe you had an unclean shutdown, please remove"
-	log_failure_msg "lockfiles and retry starting $prog"
-	RETVAL=1
-	return ${RETVAL}
-    fi
-
-    if [ -f ${update_pid_file} ]; then
+    if [ -r ${update_pid_file} ]; then
 	ps $(cat ${update_pid_file}) >/dev/null 2>&1
 	if [ ! $? = 0 ]; then
-	    log_failure_msg "bdii-update pid file exists: ${update_pid_file} but the update process died"
+	    log_failure_msg "$prog pid file exists but the process died"
 	    RETVAL=1
 	    return ${RETVAL}
 	fi
     else
-	log_failure_msg "slapd lock file: $slapd_lock_file and/or"
-	log_failure_msg "bdii-update lock file: ${update_lock_file} exists but"
-	log_failure_msg "update process pid file: ${update_pid_file} does not exist"
-	log_failure_msg "maybe you had an unclean shutdown, please remove"
-	log_failure_msg "lockfiles and retry starting $prog"
+	log_failure_msg "$prog process has no pid file"
 	RETVAL=1
 	return ${RETVAL}
     fi
 
-    log_success_msg "BDII Running"
+    log_success_msg "$prog is running"
+
     RETVAL=0
     return ${RETVAL}
 }
@@ -360,7 +328,7 @@ case "$1" in
 	status
 	;;
     condrestart | try-restart)
-	if [ -f ${slapd_lock_file} ]; then
+	if [ -r ${update_lock_file} ]; then
 	    stop
 	    # avoid race
 	    sleep 3
