Make infosys_ldap_run_dir (/var/run/arc/infosys) configurable (bz #3185)

diff --git a/src/services/ldap-infosys/nordugrid-arc-bdii.in b/src/services/ldap-infosys/nordugrid-arc-bdii.in
--- a/src/services/ldap-infosys/nordugrid-arc-bdii.in
+++ b/src/services/ldap-infosys/nordugrid-arc-bdii.in
@@ -87,8 +87,9 @@ fi
 
 ARC_CONFIG=${ARC_CONFIG:-/etc/arc.conf}
 if [ ! -r "$ARC_CONFIG" ]; then
-    log_failure_msg "arc.conf was not found. If this file is in a non-standard place,"
-    log_failure_msg "  it can be set with the ARC_CONFIG environment variable"
+    log_failure_msg "ARC configuration file ($ARC_CONFIG) not found"
+    log_failure_msg "If this file is in a non-standard place it can be set"
+    log_failure_msg "  with the ARC_CONFIG environment variable"
     exit 1
 fi
 
@@ -97,8 +98,8 @@ config_parse_file $ARC_CONFIG || exit $?
 
 # Check for infosys-block
 if ! config_match_section infosys; then
-    log_warning_msg "Missing infosys configuration block"
-    exit 0
+    log_failure_msg "Missing infosys configuration block"
+    exit 1
 fi
 
 config_hide_all
@@ -138,14 +139,14 @@ fi
 # If missing, we have a problem
 USERSHELL=${USERSHELL:-"/bin/sh"}
 if [ ! -x ${USERSHELL} ]; then
-    log_failure_msg "Could not find /bin/sh"
+    log_failure_msg "Could not find ${USERSHELL}"
     exit 1
 fi
 
 bdii_location=${CONFIG_bdii_location:-/usr}
 giis_location=${CONFIG_giis_location:-$ARC_LOCATION}
 
-bdii_update_cmd=${CONFIG_bdii_update_cmd:-"${bdii_location}/sbin/bdii-update"}
+bdii_update_cmd=${CONFIG_bdii_update_cmd:-${bdii_location}/sbin/bdii-update}
 if [ ! -e $bdii_update_cmd ]; then
     log_failure_msg "Can not find bdii-update command at: $bdii_update_cmd."
     log_failure_msg "Please set bdii_update_cmd in arc.conf"
@@ -160,10 +161,10 @@ if grep -q BDII_PID_FILE $bdii_update_cmd ; then
     bdii_run_dir=${CONFIG_bdii_run_dir:-/var/run/arc/bdii}
 else
     bdii_var_dir=${CONFIG_bdii_var_dir:-/var/run/arc/bdii}
-    bdii_run_dir=$bdii_var_dir
+    bdii_run_dir=${bdii_var_dir}
 fi
 bdii_log_dir=${CONFIG_bdii_log_dir:-/var/log/arc/bdii}
-bdii_log_file="${bdii_log_dir}/bdii-update.log"
+bdii_log_file=${bdii_log_dir}/bdii-update.log
 
 mkdir -p $bdii_log_dir
 
@@ -190,8 +191,8 @@ fi
 
 chown ${bdii_user}: ${bdii_log_dir}
 
-arc_runtime_config="/var/run/arc/infosys"
-BDII_CONF=${CONFIG_bdii_conf:-${arc_runtime_config}/bdii.conf}
+infosys_ldap_run_dir=${CONFIG_infosys_ldap_run_dir:-/var/run/arc/infosys}
+BDII_CONF=${CONFIG_bdii_conf:-${infosys_ldap_run_dir}/bdii.conf}
 
 start () {
     if [ -r "${update_lock_file}" ]; then
@@ -202,7 +203,7 @@ start () {
 
     ${ARC_LOCATION}/@pkgdatasubdir@/create-bdii-config
     if [ ! $? = 0 ]; then
-	log_failure_msg "Failed to create configration for $prog"
+	log_failure_msg "Failed to create configuration for $prog"
 	exit 1
     fi
 
@@ -214,13 +215,12 @@ start () {
 	sleep 1
 	iterlimit=$(expr $iterlimit - 1)
     done
+
     if [ ! -r ${update_pid_file} ]; then
 	log_failure_msg "$prog failed to start"
 	rm -f ${update_lock_file}
-	exit 1
-    else
-	touch ${update_lock_file}
-	RETVAL=0
+	RETVAL=1
+	return ${RETVAL}
     fi
 
     log_success_msg "$prog started"
@@ -266,22 +266,15 @@ stop () {
 	fi
     fi
 
+    # Clean up
+    rm -f ${infosys_ldap_run_dir}/arc-glue-bdii-ldif
+
     if [ ${RETVAL} = 0 ];  then
 	rm -f ${update_pid_file}
 	rm -f ${update_lock_file}
+	log_success_msg "$prog stopped"
     else
 	log_failure_msg "Could not kill $prog with pid ${update_pid}"
-    fi
-
-    # Clean up
-    rm -f ${arc_runtime_config}/arc-glue-bdii-ldif
-
-    if [ ! ${RETVAL} = 0 ];  then
-	log_failure_msg
-	return 1
-    else
-	rm -f ${update_lock_file}
-	log_success_msg "$prog stopped"
     fi
 
     return ${RETVAL}
@@ -303,7 +296,7 @@ status ()  {
 	fi
     else
 	log_failure_msg "$prog process has no pid file"
-	RETVAL=1
+	RETVAL=2
 	return ${RETVAL}
     fi
 
diff --git a/src/services/ldap-infosys/nordugrid-arc-inforeg.in b/src/services/ldap-infosys/nordugrid-arc-inforeg.in
--- a/src/services/ldap-infosys/nordugrid-arc-inforeg.in
+++ b/src/services/ldap-infosys/nordugrid-arc-inforeg.in
@@ -23,7 +23,7 @@
 ### END INIT INFO
 
 # Helper functions
-if [ -f /etc/init.d/functions ]; then
+if [ -r /etc/init.d/functions ]; then
     . /etc/init.d/functions
     log_success_msg() {
         echo -n "$@"
@@ -40,7 +40,7 @@ if [ -f /etc/init.d/functions ]; then
         failure "$@"
         echo
     }
-elif [ -f /lib/lsb/init-functions ]; then
+elif [ -r /lib/lsb/init-functions ]; then
     . /lib/lsb/init-functions
 else
     echo "Error: Cannot source neither init.d nor lsb functions"
@@ -63,18 +63,18 @@ elif [ -r /etc/default/$prog ]; then
     . /etc/default/$prog
 fi
 
-[ -n "$ARC_LOCATION ] && export ARC_LOCATION
-[ -n "$ARC_CONFIG ]   && export ARC_CONFIG
-
 if [ "x$RUN" != "xyes" ]; then
-    echo "$prog disabled, please adjust the configuration to your needs "
-    echo "and then set RUN to 'yes' in /etc/default/$prog to enable it."
+    log_warning_msg "$prog disabled, please adjust the configuration to your"
+    log_warning_msg "needs and then set RUN to 'yes' in /etc/default/$prog to enable it."
     exit 0
 fi
 
+[ -n "$ARC_LOCATION" ] && export ARC_LOCATION
+[ -n "$ARC_CONFIG" ]   && export ARC_CONFIG
+
 ARC_LOCATION=${ARC_LOCATION:-@prefix@}
 if [ ! -d "$ARC_LOCATION" ]; then
-    echo "ARC_LOCATION ($ARC_LOCATION) not found"
+    log_failure_msg "ARC_LOCATION ($ARC_LOCATION) not found"
     exit 1
 fi
 
@@ -82,15 +82,15 @@ fi
 if [ -r "$ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh" ]; then
     . $ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh || exit $?
 else
-    echo "Could not find $ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh"
+    log_failure_msg "Could not find $ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh"
     exit 1
 fi
 
 ARC_CONFIG=${ARC_CONFIG:-/etc/arc.conf}
 if [ ! -r "$ARC_CONFIG" ]; then
-    echo "ARC configuration file ($ARC_CONFIG) not found"
-    echo "If this file is in a non-standard place it can be set with the"
-    echo "  ARC_CONFIG environment variable"
+    log_failure_msg "ARC configuration file ($ARC_CONFIG) not found"
+    log_failure_msg "If this file is in a non-standard place it can be set"
+    log_failure_msg "  with the ARC_CONFIG environment variable"
     exit 1
 fi
 
@@ -99,8 +99,8 @@ config_parse_file $ARC_CONFIG || exit $?
 
 # Check for infosys-block
 if ! config_match_section infosys; then
-    echo "Missing infosys configuration block"
-    exit 0
+    log_failure_msg "Missing infosys configuration block"
+    exit 1
 fi
 
 config_hide_all
@@ -117,7 +117,7 @@ fi
 # If missing, we have a problem
 USERSHELL=${USERSHELL:-"/bin/sh"}
 if [ ! -x ${USERSHELL} ]; then
-    log_failure_msg "Could not find /bin/sh"
+    log_failure_msg "Could not find ${USERSHELL}"
     exit 1
 fi
 
@@ -129,9 +129,9 @@ else
 fi
 
 registrationlog=${CONFIG_registrationlog:-/var/log/arc/inforegistration.log}
-arc_runtime_config="/var/run/arc/infosys"
-registrationconf=$arc_runtime_config/grid-info-resource-register.conf
-pid_file="/var/run/nordugrid-arc-inforeg.pid"
+infosys_ldap_run_dir=${CONFIG_infosys_ldap_run_dir:-/var/run/arc/infosys}
+registrationconf=${infosys_ldap_run_dir}/grid-info-resource-register.conf
+pid_file=${CONFIG_registration_pid_file:-/var/run/nordugrid-arc-inforeg.pid}
 
 start () {
     echo -n "Starting $prog: "
diff --git a/src/services/ldap-infosys/nordugrid-arc-slapd.in b/src/services/ldap-infosys/nordugrid-arc-slapd.in
--- a/src/services/ldap-infosys/nordugrid-arc-slapd.in
+++ b/src/services/ldap-infosys/nordugrid-arc-slapd.in
@@ -77,8 +77,47 @@ if [ ! -d "$ARC_LOCATION" ]; then
     exit 1
 fi
 
-bdii_run_dir=/var/run/arc/bdii
-slapd_pid_file=$bdii_run_dir/db/slapd.pid
+# Source the config parsing routines
+if [ -r "$ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh" ]; then
+    . $ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh || exit $?
+else
+    log_failure_msg "Could not find $ARC_LOCATION/@pkgdatasubdir@/config_parser_compat.sh"
+    exit 1
+fi
+
+ARC_CONFIG=${ARC_CONFIG:-/etc/arc.conf}
+if [ ! -r "$ARC_CONFIG" ]; then
+    log_failure_msg "ARC configuration file ($ARC_CONFIG) not found"
+    log_failure_msg "If this file is in a non-standard place it can be set"
+    log_failure_msg "  with the ARC_CONFIG environment variable"
+    exit 1
+fi
+
+# Read arc.conf
+config_parse_file $ARC_CONFIG || exit $?
+
+# Check for infosys-block
+if ! config_match_section infosys; then
+    log_failure_msg "Missing infosys configuration block"
+    exit 1
+fi
+
+config_hide_all
+config_import_section common
+config_import_section infosys
+
+bdii_location=${CONFIG_bdii_location:-/usr}
+bdii_update_cmd=${CONFIG_bdii_update_cmd:-${bdii_location}/sbin/bdii-update}
+if [ ! -x $bdii_update_cmd ] || grep -q BDII_PID_FILE $bdii_update_cmd; then
+    bdii_var_dir=${CONFIG_bdii_var_dir:-/var/lib/arc/bdii}
+    bdii_run_dir=${CONFIG_bdii_run_dir:-/var/run/arc/bdii}
+else
+    bdii_var_dir=${CONFIG_bdii_var_dir:-/var/run/arc/bdii}
+    bdii_run_dir=${bdii_var_dir}
+fi
+slapd_pid_file=${bdii_run_dir}/db/slapd.pid
+
+infosys_ldap_run_dir=${CONFIG_infosys_ldap_run_dir:-/var/run/arc/infosys}
 
 # Debian does not have /var/lock/subsys
 if [ -d /var/lock/subsys ]; then
@@ -99,7 +138,7 @@ start () {
 	log_failure_msg "Failed to create configuration for $prog"
 	exit 1
     fi
-    /bin/sh /var/run/arc/infosys/bdii-slapd.cmd
+    /bin/sh ${infosys_ldap_run_dir}/bdii-slapd.cmd
 
     touch ${slapd_lock_file}
 
@@ -118,8 +157,9 @@ start () {
 
     log_success_msg "$prog started"
 
-    if [ -x "/etc/init.d/nordugrid-arc-bdii" ] ; then
-	/etc/init.d/nordugrid-arc-bdii condrestart
+    prefix=${ARC_LOCATION:-@prefix@}
+    if [ -x @initddir@/nordugrid-arc-bdii ] ; then
+	@initddir@/nordugrid-arc-bdii condrestart
     fi
 }
 
@@ -155,19 +195,18 @@ stop () {
 		sleep 2
 		ps ${slapd_pid} >/dev/null 2>&1
 		if [ $? = 0 ]; then
-		    RETVAL=2
-		else
-		    rm -f {slapd_pid_file}
+		    RETVAL=1
 		fi
 	    fi
 	fi
     fi
 
-    if [ ${RETVAL} = 2 ];  then
-	log_failure_msg "Could not stop $prog with pid: $slapd_pid"
-    else
+    if [ ${RETVAL} = 0 ];  then
+	rm -f ${slapd_pid_file}
 	rm -f ${slapd_lock_file}
 	log_success_msg "$prog stopped"
+    else
+	log_failure_msg "Could not stop $prog with pid: $slapd_pid"
     fi
 
     return ${RETVAL}
@@ -189,7 +228,7 @@ status ()  {
 	fi
     else
 	log_failure_msg "$prog process has no pid file"
-	RETVAL=1
+	RETVAL=2
 	return ${RETVAL}
     fi
 
