@sbindir@ is not resolved fully on some platforms only to the level of ${exec_prefix}/sbin which is not enough. @prefix@ is resolved fully during configure.
The solution is to use @prefix@/sbin instead of @sbindir@. This
is not ideal but works. In addition we use the ARC_LOCATION
solution from gridftpd.

This fixes bug #2099.

diff --git a/src/hed/daemon/scripts/arched.in b/src/hed/daemon/scripts/arched.in
--- a/src/hed/daemon/scripts/arched.in
+++ b/src/hed/daemon/scripts/arched.in
@@ -53,9 +53,24 @@ else
     exit 1
 fi
 
+NAME=arched
+
+# ARC_LOCATION
+ARC_LOCATION=${ARC_LOCATION:-@prefix@}
+if [ ! -d "$ARC_LOCATION" ]; then
+  echo "ARC_LOCATION ($ARC_LOCATION) not found"
+  exit 1
+fi
+export ARC_LOCATION
+
+DAEMON="$ARC_LOCATION/sbin/$NAME"
+if ! test -x "$DAEMON"; then
+    failure "Missing executable"
+    echo
+    exit 1
+fi
+
 RUN=yes
-DAEMON=@sbindir@/arched
-NAME=`basename $DAEMON`
 
 if [ -f /etc/sysconfig/$NAME ]; then
     . /etc/sysconfig/$NAME
