common scan/cancell for all shell-backends

diff --git a/src/services/a-rex/lrms/boinc/scan-boinc-job.in b/src/services/a-rex/lrms/boinc/scan-boinc-job.in
--- a/src/services/a-rex/lrms/boinc/scan-boinc-job.in
+++ b/src/services/a-rex/lrms/boinc/scan-boinc-job.in
@@ -18,16 +18,23 @@ debug "options = $@"
 
 # ARC1 passes first the config file.
 if [ "$1" = "--config" ]; then shift; ARC_CONFIG=$1; shift; fi
+if [ -z "$1" ] ; then echo "Controldir argument missing" 1>&2 ; exit 1 ; fi
 
+joboption_lrms="boinc"
+
+# define paths and config parser
 basedir=`dirname $0`
 basedir=`cd $basedir > /dev/null && pwd` || exit $?
+. "${basedir}/lrms_common.sh"
 
-pkglibexecdir="${ARC_LOCATION:-@prefix@}/@pkglibexecsubdir@"
-pkgdatadir="$basedir"
+# include common scan functions
+. "${pkgdatadir}/scan_common.sh" || exit $?
 
-. "${pkgdatadir}/configure-boinc-env.sh" || exit $?
-
-if [ -z "$1" ] ; then echo "Argument missing" 1>&2 ; exit 1 ; fi
+# run common init 
+#  * parse config
+#  * load LRMS-specific env
+#  * set common variables
+common_init
 
 GMKICK=${pkglibexecdir}/gm-kick
 
diff --git a/src/services/a-rex/lrms/fork/scan-fork-job.in b/src/services/a-rex/lrms/fork/scan-fork-job.in
--- a/src/services/a-rex/lrms/fork/scan-fork-job.in
+++ b/src/services/a-rex/lrms/fork/scan-fork-job.in
@@ -14,10 +14,19 @@ $debug "options = $@"
 
 # ARC1 passes first the config file.
 if [ "$1" = "--config" ]; then shift; ARC_CONFIG=$1; shift; fi
+if [ -z "$1" ] ; then echo "Controldir argument missing" 1>&2 ; exit 1 ; fi
 
-if [ -z "$1" ] ; then echo "Argument missing" 1>&2 ; exit 1 ; fi
+# define paths and config parser
+basedir=`dirname $0`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
+. "${basedir}/lrms_common.sh"
 
-libexecdir="${ARC_LOCATION:-@prefix@}/@pkglibexecsubdir@/"
+# include common scan functions
+. "${pkgdatadir}/scan_common.sh" || exit $?
+
+# no arc.conf parsing needed as well as LRMS-specific config
+#common_init
+
 GMKICK=${libexecdir}/gm-kick
 
 # Prints the uid of the owner of the file given as argument
diff --git a/src/services/a-rex/lrms/lsf/scan-lsf-job.in b/src/services/a-rex/lrms/lsf/scan-lsf-job.in
--- a/src/services/a-rex/lrms/lsf/scan-lsf-job.in
+++ b/src/services/a-rex/lrms/lsf/scan-lsf-job.in
@@ -10,36 +10,12 @@
 
 # ARC1 passes first the config file.
 if [ "$1" = "--config" ]; then shift; ARC_CONFIG=$1; shift; fi
-
-basedir=`dirname $0`
-basedir=`cd $basedir > /dev/null && pwd` || exit $?
-
-pkglibexecdir="${ARC_LOCATION:-@prefix@}/@pkglibexecsubdir@"
-pkgdatadir="$basedir"
-
-# Assume that gm-kick is installed in the same directory
-GMKICK=${pkglibexecdir}/gm-kick
-
-. "${pkgdatadir}/configure-lsf-env.sh" || exit $?
-
-. "${pkgdatadir}/scan_common.sh" || exit $?
-
-umask 022
-
 if [ -z "$1" ] ; then
-    echo "Missing Input Script file as arg1" 1>&2
-    exit 1 ;
+    echo "Missing control directory path" 1>&2
+    exit 1
 fi
-
-# Log system performance
-if [ ! -z "$perflogdir" ]; then
-   perflog_common "$perflogdir" "$CONFIG_controldir"
-fi
-
 # first control_dir is used for storing own files
-
 echo `date`" : control_dir=$1" 1>&2
-
 control_dir=$1
 control_dirs=
 while [ $# -gt 0 ] ; do
@@ -47,20 +23,44 @@ while [ $# -gt 0 ] ; do
   shift
 done
 
-my_id=`id -u`
+joboption_lrms="lsf"
 
-# Get all running jobs
-#
+# define paths and config parser
+basedir=`dirname $0`
+basedir=`cd $basedir > /dev/null && pwd` || exit $?
+. "${basedir}/lrms_common.sh"
 
-if [ -z ${LSF_BIN_PATH} ]; then
-    echo "${LSF_BIN_PATH} not set" 1>&2
-    exit 1
+# include common scan functions
+. "${pkgdatadir}/scan_common.sh" || exit $?
+
+# run common init 
+#  * parse config
+#  * load LRMS-specific env
+#  * set common variables
+common_init
+
+# Assume that gm-kick is installed in the same directory
+GMKICK=${pkglibexecdir}/gm-kick
+
+umask 022
+
+# Log system performance
+if [ ! -z "$perflogdir" ]; then
+   perflog_common "$perflogdir" "$CONFIG_controldir"
 fi
 
 if [ ! -z "$perflogdir" ]; then
    start_ts=`date +%s.%N`
 fi
 
+my_id=`id -u`
+
+if [ -z ${LSF_BIN_PATH} ]; then
+    echo "${LSF_BIN_PATH} not set" 1>&2
+    exit 1
+fi
+
+# Get all running jobs
 lsf_stat=`${LSF_BIN_PATH}/bjobs -a -u all 2>/dev/null` # | grep RUN | grep '^ [:digit:]'
 
 if [ ! -z "$perflogdir" ]; then
